In [1]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df_city_indonesia = pd.read_excel('/content/drive/MyDrive/TAN DIGITAL/City Indonesia.xlsx')
df_city_indonesia

# # Membaca file Excel dengan nama 'City Indonesia.xlsx'
# df_city_indonesia = pd.read_excel('City Indonesia.xlsx')
# df_city_indonesia.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,City,CityCode,Province,Region,RegionalCode
0,Kabupaten Aceh Barat,MBO,Provinsi Aceh,Sumbagut,1
1,Kabupaten Aceh Barat Daya,BPD,Provinsi Aceh,Sumbagut,1
2,Kabupaten Aceh Besar,JTH,Provinsi Aceh,Sumbagut,1
3,Kabupaten Aceh Jaya,CAG,Provinsi Aceh,Sumbagut,1
4,Kabupaten Aceh Selatan,TTN,Provinsi Aceh,Sumbagut,1
...,...,...,...,...,...
509,Kota Ternate,TTE,Provinsi Maluku Utara,Sulawesi,10
510,Kota Tidore Kepulauan,TDR,Provinsi Maluku Utara,Sulawesi,10
511,Kota Tomohon,TMH,Provinsi Sulawesi Utara,Sulawesi,10
512,Kota Tual,TUL,Provinsi Maluku,Puma,11
513,Kota Yogyakarta,YYK,DI Yogyakarta,Jawa Tengah,6

In [2]:
# Check for required fields
df_city_indonesia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          514 non-null    object
 1   CityCode      514 non-null    object
 2   Province      514 non-null    object
 3   Region        514 non-null    object
 4   RegionalCode  514 non-null    int64
dtypes: int64(1), object(4)
memory usage: 20.2+ KB

In [3]:
df_city_indonesia.columns

Index(['City', 'CityCode', 'Province', 'Region', 'RegionalCode'], dtype='object')

In [4]:
df_assessment = pd.read_excel('/content/drive/MyDrive/TAN DIGITAL/Assessment Data Asset Dummy.xlsx')
df_assessment

# # Membaca file Excel dengan nama 'Assessment Data Asset Dummy.xlsx'
# df_assessment = pd.read_excel('Assessment Data Asset Dummy.xlsx')
# df_assessment.head()

,Funcloc,Alamat1,Alamat2,Alamat3,Alamat4,SiteName
0,100000000002,Desa Alun Dua,Desa Alun Dua,Kecamatan Kerkap,BENGKULU UTARA,Steele-Phillips
1,100000000003,Desa Padang Maninjau,Kel. Desa Padang Maninjau,Kec. Aek Kuo,LABUHANBATU UTARA,"Herrera, Barnes and Taylor"
2,100000000004,Desa Bio-Bio,Kel. Bandar Durian,Kec. Aek Natas,LABUHANBATU UTARA,Lee Group
3,100000000005,Rintis Kacang,Desa Pangakalan,Kec. Aek Natas,LABUHANBATU UTARA,Barton Inc
4,100000000006,Dusun VI Sidodadi,Desa Marbau Selatan,Kec. Marbau,LABUHANBATU UTARA,"Cole, Molina and Williams"
...,...,...,...,...,...,...
4903,100000059183,Dusun Tiga Desa Aek Nauli 2 Kec.Pollung,Ds Aek Nauli 2,Pollung,Humbang Hasundutan,Hurley Inc
4904,100000059265,Desa Pansur Natolu Kec.Pangaribuan,Ds Pansur Natolu,Pangaribuan,Tapanuli Utara,Wright-Garza
4905,100000059267,Jl.Banglas Gg Damai RT.02/02,Ds Selatpanjang Timur,Tebing Tinggi,Kepulauan Meranti,Benton-Perez
4906,100000059268,Desa Banuaji I Kec.Adiankoting,Ds Banuaji I,Adiankoting,Tapanuli Utara,Ingram-Brown
4907,100000059270,Desa Perjuangan Kec.Sumbul Kab.Dairi,Ds Perjuangan,Sumbul,Dairi,"Blackwell, Richards and Sanders"

In [5]:
# Check for required fields
df_assessment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4908 entries, 0 to 4907
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Funcloc   4908 non-null   int64
 1   Alamat1   4908 non-null   object
 2   Alamat2   4884 non-null   object
 3   Alamat3   4877 non-null   object
 4   Alamat4   4908 non-null   object
 5   SiteName  4908 non-null   object
dtypes: int64(1), object(5)
memory usage: 230.2+ KB

In [6]:
df_assessment.columns

Index(['Funcloc', 'Alamat1', 'Alamat2', 'Alamat3', 'Alamat4', 'SiteName'], dtype='object')

In [7]:
# Convert all string columns to uppercase, except Funcloc and RegionalCode
df_city_indonesia = df_city_indonesia.apply(
    lambda x: x.str.upper() if x.name not in ['RegionalCode'] and x.dtype == 'object' else x
)

df_assessment = df_assessment.apply(
    lambda x: x.str.upper() if x.name not in ['Funcloc'] and x.dtype == 'object' else x
)

In [8]:
df_city_indonesia

,City,CityCode,Province,Region,RegionalCode
0,KABUPATEN ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1
1,KABUPATEN ACEH BARAT DAYA,BPD,PROVINSI ACEH,SUMBAGUT,1
2,KABUPATEN ACEH BESAR,JTH,PROVINSI ACEH,SUMBAGUT,1
3,KABUPATEN ACEH JAYA,CAG,PROVINSI ACEH,SUMBAGUT,1
4,KABUPATEN ACEH SELATAN,TTN,PROVINSI ACEH,SUMBAGUT,1
...,...,...,...,...,...
509,KOTA TERNATE,TTE,PROVINSI MALUKU UTARA,SULAWESI,10
510,KOTA TIDORE KEPULAUAN,TDR,PROVINSI MALUKU UTARA,SULAWESI,10
511,KOTA TOMOHON,TMH,PROVINSI SULAWESI UTARA,SULAWESI,10
512,KOTA TUAL,TUL,PROVINSI MALUKU,PUMA,11
513,KOTA YOGYAKARTA,YYK,DI YOGYAKARTA,JAWA TENGAH,6

In [9]:
df_assessment

,Funcloc,Alamat1,Alamat2,Alamat3,Alamat4,SiteName
0,100000000002,DESA ALUN DUA,DESA ALUN DUA,KECAMATAN KERKAP,BENGKULU UTARA,STEELE-PHILLIPS
1,100000000003,DESA PADANG MANINJAU,KEL. DESA PADANG MANINJAU,KEC. AEK KUO,LABUHANBATU UTARA,"HERRERA, BARNES AND TAYLOR"
2,100000000004,DESA BIO-BIO,KEL. BANDAR DURIAN,KEC. AEK NATAS,LABUHANBATU UTARA,LEE GROUP
3,100000000005,RINTIS KACANG,DESA PANGAKALAN,KEC. AEK NATAS,LABUHANBATU UTARA,BARTON INC
4,100000000006,DUSUN VI SIDODADI,DESA MARBAU SELATAN,KEC. MARBAU,LABUHANBATU UTARA,"COLE, MOLINA AND WILLIAMS"
...,...,...,...,...,...,...
4903,100000059183,DUSUN TIGA DESA AEK NAULI 2 KEC.POLLUNG,DS AEK NAULI 2,POLLUNG,HUMBANG HASUNDUTAN,HURLEY INC
4904,100000059265,DESA PANSUR NATOLU KEC.PANGARIBUAN,DS PANSUR NATOLU,PANGARIBUAN,TAPANULI UTARA,WRIGHT-GARZA
4905,100000059267,JL.BANGLAS GG DAMAI RT.02/02,DS SELATPANJANG TIMUR,TEBING TINGGI,KEPULAUAN MERANTI,BENTON-PEREZ
4906,100000059268,DESA BANUAJI I KEC.ADIANKOTING,DS BANUAJI I,ADIANKOTING,TAPANULI UTARA,INGRAM-BROWN
4907,100000059270,DESA PERJUANGAN KEC.SUMBUL KAB.DAIRI,DS PERJUANGAN,SUMBUL,DAIRI,"BLACKWELL, RICHARDS AND SANDERS"

In [10]:
# Baris dengan NaN di df_city
print("Baris dengan NaN di df_city:")
print(df_city_indonesia[df_city_indonesia.isna().any(axis=1)])

Baris dengan NaN di df_city:
Empty DataFrame
Columns: [City, CityCode, Province, Region, RegionalCode]
Index: []

In [11]:
# Baris dengan NaN di df_assessment
print("\nBaris dengan NaN di df_assessment:")
print(df_assessment[df_assessment.isna().any(axis=1)])

Baris dengan NaN di df_assessment:
           Funcloc                                   Alamat1  \
887   100000001581          JL. SILIWANGI CIANJUR JAWA BARAT
1355  100000002441                            MAKASSAR, KOTA
1893  100000003346          JL PERJUANGAN RT 03 SAMARINDA KA
1920  100000003429     JL. RAYA CAGAK NAGREG RT. 01 / RW. 08
1922  100000003431            CIGIRINGSING WETAN RT 01 RW 19
1944  100000003484         JL. RAYA MALANGBONG - TASIKMALAYA
1945  100000003486                 JL. RAYA SUKAMANTRI KM1.5
1946  100000003487                              JL. CIPONDOK
2035  100000003714                            PULAU BIDADARI
2483  100000005423                   KOMPLEK ASTRA JL.LUKMAN
3005  100000007341      DS. KALAYAN RT12/RW03, CIREBON UTARA
3007  100000007343      JL. TANGKUBAN PERAHU 111 RT 01/RW 03
3009  100000007346                     JL. MULYASARI BANDUNG
3012  100000007351  YAYASAN MASJID AL-FATAH JL. RAYA LIMBANG
3095  100000007838    JL. ABUBAKAR LAMBOGO LORONG 12 , RT 04
3128  100000008236                          JL. GAYUNGAN PTT
3132  100000008266          GD.GRAHAPRATAMALT.5,JL.MT HARYON
3133  100000008268          GD.GRAHAPRATAMALT.5,JL.MT HARYON
3134  100000008274          GD.GRAHAPRATAMALT.5,JL.MT HARYON
3135  100000008277          GD.GRAHAPRATAMALT.5,JL.MT HARYON
3136  100000008279          GD.GRAHAPRATAMALT.5,JL.MT HARYON
3137  100000008281          GD.GRAHAPRATAMALT.5,JL.MT HARYON
3138  100000008284          GD.GRAHAPRATAMALT.5,JL.MT HARYON
3139  100000008285          GD.GRAHAPRATAMALT.5,JL.MT HARYON
3363  100000012967                  JL. JEND. SUDIRMAN MAROS
3459  100000013212                                JL MERDEKA
3685  100000014470       JL. CIKUTRA BARU VI (BLOK SEKEJATI)
3687  100000014472                JL SETIABUDI KM 10 RT03/07
3691  100000014477    JL. SUMUR BANDUNG - BANDUNG DH SIMPANG
3727  100000014527                                DS SIMPANG
3798  100000014614  JL. RAYA BREBES DESA JOGJAKARTA RT 01/01
3998  100000014877      JL. RAYA SERPONG , GG. JOHOR KP.SETU

                 Alamat2                 Alamat3              Alamat4  \
887                  NaN                     NaN              CIANJUR
1355                 NaN                     NaN       MAKASSAR, KOTA
1893                 NaN                     NaN      SAMARINDA, KOTA
1920                 NaN                     NaN              BANDUNG
1922           DESA GIRI                     NaN              BANDUNG
1944                 NaN                     NaN          TASIKMALAYA
1945                 NaN                     NaN          TASIKMALAYA
1946                 NaN                     NaN          TASIKMALAYA
2035                 NaN                     NaN  JAKARTA UTARA, KOTA
2483          KEL.AMPLAS                     NaN          MEDAN, KOTA
3005         DS. KALAYAN                     NaN        CIREBON, KOTA
3007  KEL CEBOGO LEMBANG                     NaN        BANDUNG BARAT
3009                 NaN                     NaN        BANDUNG, KOTA
3012                 NaN  KEC. BALUBUR LIMBANGAN                GARUT
3095                 NaN                     NaN       MAKASSAR, KOTA
3128                 NaN                     NaN             SURABAYA
3132                 NaN                     NaN              JAKARTA
3133                 NaN                     NaN              JAKARTA
3134                 NaN                     NaN              JAKARTA
3135                 NaN                     NaN              JAKARTA
3136                 NaN                     NaN              JAKARTA
3137                 NaN                     NaN              JAKARTA
3138                 NaN                     NaN              JAKARTA
3139                 NaN                     NaN              JAKARTA
3363                 NaN                     NaN                MAROS
3459                LAPE                     NaN              SANGGAU
3685       KEL NEGLASARI                     NaN        BANDUNG, KOTA
3687                 NaN                     NaN        BANDUNG, KOTA
3691                 NaN                     NaN        BANDUNG, KOTA
3727          DS SIMPANG                     NaN              CIANJUR
3798     DESA JOGJAKARTA                     NaN      LAMPUNG SELATAN
3998                 NaN                     NaN            TANGERANG

                            SiteName
887                 CARPENTER-WATSON
1355       FLORES, ROACH AND RAMIREZ
1893     DIAZ, CARPENTER AND COLLINS
1920                  FOSTER-SWANSON
1922       MCMAHON, WOOD AND COLEMAN
1944                      POWELL INC
1945                  PETERSON GROUP
1946                  HOWELL-SPENCER
2035                 JOHNSON-JOHNSON
2483                 CERVANTES-BROWN
3005    JOHNSON, JACKSON AND SHIELDS
3007                      FINLEY INC
3009                   PETERS-MARTIN
3012                  WRIGHT-ELLIOTT
3095                WASHINGTON GROUP
3128        MYERS, ALLISON AND HODGE
3132    MACIAS, MCGUIRE AND MITCHELL
3133                KNIGHT-RODRIGUEZ
3134                     JOHNSON INC
3135                    THOMAS GROUP
3136                     WATKINS INC
3137  FULLER, CERVANTES AND STEPHENS
3138                    HARRIS GROUP
3139                BLACKWELL-MEDINA
3363                  PEREZ-MARSHALL
3459               CALDERON AND SONS
3685                    VALENCIA LLC
3687                     CAMACHO LTD
3691    HAWKINS, WILSON AND MARTINEZ
3727               STRICKLAND-MASSEY
3798                    ROMAN-WATSON
3998                       PEREZ PLC

In [12]:
# Baris dengan NaN di kolom Funcloc dan Alamat4
print("\nBaris dengan NaN di kolom Funcloc dan Alamat4:")
print(df_assessment[df_assessment[['Funcloc', 'Alamat4']].isna().any(axis=1)])

Baris dengan NaN di kolom Funcloc dan Alamat4:
Empty DataFrame
Columns: [Funcloc, Alamat1, Alamat2, Alamat3, Alamat4, SiteName]
Index: []

In [13]:
# Menampilkan nilai unik pada kolom City
unique_cities = df_city_indonesia['City'].unique()

# Menampilkan hasil
print(unique_cities)

['KABUPATEN ACEH BARAT' 'KABUPATEN ACEH BARAT DAYA' 'KABUPATEN ACEH BESAR'
 'KABUPATEN ACEH JAYA' 'KABUPATEN ACEH SELATAN' 'KABUPATEN ACEH SINGKIL'
 'KABUPATEN ACEH TAMIANG' 'KABUPATEN ACEH TENGAH'
 'KABUPATEN ACEH TENGGARA' 'KABUPATEN ACEH TIMUR' 'KABUPATEN ACEH UTARA'
 'KABUPATEN ADM. KEPULAUAN SERIBU' 'KABUPATEN AGAM' 'KABUPATEN ALOR'
 'KABUPATEN ASAHAN' 'KABUPATEN ASMAT' 'KABUPATEN BADUNG'
 'KABUPATEN BALANGAN' 'KABUPATEN BANDUNG' 'KABUPATEN BANDUNG BARAT'
 'KABUPATEN BANGGAI' 'KABUPATEN BANGGAI KEPULAUAN'
 'KABUPATEN BANGGAI LAUT' 'KABUPATEN BANGKA' 'KABUPATEN BANGKA BARAT'
 'KABUPATEN BANGKA SELATAN' 'KABUPATEN BANGKA TENGAH'
 'KABUPATEN BANGKALAN' 'KABUPATEN BANGLI' 'KABUPATEN BANJAR'
 'KABUPATEN BANJARNEGARA' 'KABUPATEN BANTAENG' 'KABUPATEN BANTUL'
 'KABUPATEN BANYUASIN' 'KABUPATEN BANYUMAS' 'KABUPATEN BANYUWANGI'
 'KABUPATEN BARITO KUALA' 'KABUPATEN BARITO SELATAN'
 'KABUPATEN BARITO TIMUR' 'KABUPATEN BARITO UTARA' 'KABUPATEN BARRU'
 'KABUPATEN BATANG' 'KABUPATEN BATANGHARI' 'KABUPATEN BATU BARA'
 'KABUPATEN BEKASI' 'KABUPATEN BELITUNG' 'KABUPATEN BELITUNG TIMUR'
 'KABUPATEN BELU' 'KABUPATEN BENER MERIAH' 'KABUPATEN BENGKALIS'
 'KABUPATEN BENGKAYANG' 'KABUPATEN BENGKULU SELATAN'
 'KABUPATEN BENGKULU TENGAH' 'KABUPATEN BENGKULU UTARA' 'KABUPATEN BERAU'
 'KABUPATEN BIAK NUMFOR' 'KABUPATEN BIMA' 'KABUPATEN BINTAN'
 'KABUPATEN BIREUEN' 'KABUPATEN BLITAR' 'KABUPATEN BLORA'
 'KABUPATEN BOALEMO' 'KABUPATEN BOGOR' 'KABUPATEN BOJONEGORO'
 'KABUPATEN BOLAANG MONGONDOW' 'KABUPATEN BOLAANG MONGONDOW SELATAN'
 'KABUPATEN BOLAANG MONGONDOW TIMUR' 'KABUPATEN BOLAANG MONGONDOW UTARA'
 'KABUPATEN BOMBANA' 'KABUPATEN BONDOWOSO' 'KABUPATEN BONE'
 'KABUPATEN BONE BOLANGO' 'KABUPATEN BOVEN DIGOEL' 'KABUPATEN BOYOLALI'
 'KABUPATEN BREBES' 'KABUPATEN BULELENG' 'KABUPATEN BULUKUMBA'
 'KABUPATEN BULUNGAN' 'KABUPATEN BUNGO' 'KABUPATEN BUOL' 'KABUPATEN BURU'
 'KABUPATEN BURU SELATAN' 'KABUPATEN BUTON' 'KABUPATEN BUTON SELATAN'
 'KABUPATEN BUTON TENGAH' 'KABUPATEN BUTON UTARA' 'KABUPATEN CIAMIS'
 'KABUPATEN CIANJUR' 'KABUPATEN CILACAP' 'KABUPATEN CIREBON'
 'KABUPATEN DAIRI' 'KABUPATEN DEIYAI (DELIYAI)' 'KABUPATEN DELI SERDANG'
 'KABUPATEN DEMAK' 'KABUPATEN DHARMASRAYA' 'KABUPATEN DOGIYAI'
 'KABUPATEN DOMPU' 'KABUPATEN DONGGALA' 'KABUPATEN EMPAT LAWANG'
 'KABUPATEN ENDE' 'KABUPATEN ENREKANG' 'KABUPATEN FAKFAK'
 'KABUPATEN FLORES TIMUR' 'KABUPATEN GARUT' 'KABUPATEN GAYO LUES'
 'KABUPATEN GIANYAR' 'KABUPATEN GORONTALO' 'KABUPATEN GORONTALO UTARA'
 'KABUPATEN GOWA' 'KABUPATEN GRESIK' 'KABUPATEN GROBOGAN'
 'KABUPATEN GUNUNG KIDUL' 'KABUPATEN GUNUNG MAS'
 'KABUPATEN HALMAHERA BARAT' 'KABUPATEN HALMAHERA SELATAN'
 'KABUPATEN HALMAHERA TENGAH' 'KABUPATEN HALMAHERA TIMUR'
 'KABUPATEN HALMAHERA UTARA' 'KABUPATEN HULU SUNGAI SELATAN'
 'KABUPATEN HULU SUNGAI TENGAH' 'KABUPATEN HULU SUNGAI UTARA'
 'KABUPATEN HUMBANG HASUNDUTAN' 'KABUPATEN INDRAGIRI HILIR'
 'KABUPATEN INDRAGIRI HULU' 'KABUPATEN INDRAMAYU' 'KABUPATEN INTAN JAYA'
 'KABUPATEN JAYAPURA' 'KABUPATEN JAYAWIJAYA' 'KABUPATEN JEMBER'
 'KABUPATEN JEMBRANA' 'KABUPATEN JENEPONTO' 'KABUPATEN JEPARA'
 'KABUPATEN JOMBANG' 'KABUPATEN KAIMANA' 'KABUPATEN KAMPAR'
 'KABUPATEN KAPUAS' 'KABUPATEN KAPUAS HULU' 'KABUPATEN KARANGANYAR'
 'KABUPATEN KARANGASEM' 'KABUPATEN KARAWANG' 'KABUPATEN KARIMUN'
 'KABUPATEN KARO' 'KABUPATEN KATINGAN' 'KABUPATEN KAUR'
 'KABUPATEN KAYONG UTARA' 'KABUPATEN KEBUMEN' 'KABUPATEN KEDIRI'
 'KABUPATEN KEEROM' 'KABUPATEN KENDAL' 'KABUPATEN KEPAHIANG'
 'KABUPATEN KEPULAUAN ANAMBAS' 'KABUPATEN KEPULAUAN ARU'
 'KABUPATEN KEPULAUAN MENTAWAI' 'KABUPATEN KEPULAUAN MERANTI'
 'KABUPATEN KEPULAUAN SANGIHE' 'KABUPATEN KEPULAUAN SELAYAR'
 'KABUPATEN KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)'
 'KABUPATEN KEPULAUAN SULA' 'KABUPATEN KEPULAUAN TALAUD'
 'KABUPATEN KEPULAUAN YAPEN (YAPEN WAROPEN)' 'KABUPATEN KERINCI'
 'KABUPATEN KETAPANG' 'KABUPATEN KLATEN' 'KABUPATEN KLUNGKUNG'
 'KABUPATEN KOLAKA' 'KABUPATEN KOLAKA TIMUR' 'KABUPATEN KOLAKA UTARA'
 'KABUPATEN KONAWE' 'KABUPATEN KONAWE KEPULAUAN'
 'KABUPATEN KONAWE SELATAN' 'KABUPATEN KONAWE UTARA' 'KABUPATEN KOTABARU'
 'KABUPATEN KOTAWARINGIN BARAT' 'KABUPATEN KOTAWARINGIN TIMUR'
 'KABUPATEN KUANTAN SINGINGI' 'KABUPATEN KUBU RAYA' 'KABUPATEN KUDUS'
 'KABUPATEN KULON PROGO' 'KABUPATEN KUNINGAN' 'KABUPATEN KUPANG'
 'KABUPATEN KUTAI BARAT' 'KABUPATEN KUTAI KARTANEGARA'
 'KABUPATEN KUTAI TIMUR' 'KABUPATEN LABUHANBATU'
 'KABUPATEN LABUHANBATU SELATAN' 'KABUPATEN LABUHANBATU UTARA'
 'KABUPATEN LAHAT' 'KABUPATEN LAMANDAU' 'KABUPATEN LAMONGAN'
 'KABUPATEN LAMPUNG BARAT' 'KABUPATEN LAMPUNG SELATAN'
 'KABUPATEN LAMPUNG TENGAH' 'KABUPATEN LAMPUNG TIMUR'
 'KABUPATEN LAMPUNG UTARA' 'KABUPATEN LANDAK' 'KABUPATEN LANGKAT'
 'KABUPATEN LANNY JAYA' 'KABUPATEN LEBAK' 'KABUPATEN LEBONG'
 'KABUPATEN LEMBATA' 'KABUPATEN LIMA PULUH KOTA' 'KABUPATEN LINGGA'
 'KABUPATEN LOMBOK BARAT' 'KABUPATEN LOMBOK TENGAH'
 'KABUPATEN LOMBOK TIMUR' 'KABUPATEN LOMBOK UTARA' 'KABUPATEN LUMAJANG'
 'KABUPATEN LUWU' 'KABUPATEN LUWU TIMUR' 'KABUPATEN LUWU UTARA'
 'KABUPATEN MADIUN' 'KABUPATEN MAGELANG' 'KABUPATEN MAGETAN'
 'KABUPATEN MAHAKAM ULU' 'KABUPATEN MAJALENGKA' 'KABUPATEN MAJENE'
 'KABUPATEN MALAKA' 'KABUPATEN MALANG' 'KABUPATEN MALINAU'
 'KABUPATEN MALUKU BARAT DAYA' 'KABUPATEN MALUKU TENGAH'
 'KABUPATEN MALUKU TENGGARA' 'KABUPATEN MALUKU TENGGARA BARAT'
 'KABUPATEN MAMASA' 'KABUPATEN MAMBERAMO RAYA'
 'KABUPATEN MAMBERAMO TENGAH' 'KABUPATEN MAMUJU' 'KABUPATEN MAMUJU TENGAH'
 'KABUPATEN MAMUJU UTARA' 'KABUPATEN MANDAILING NATAL'
 'KABUPATEN MANGGARAI' 'KABUPATEN MANGGARAI BARAT'
 'KABUPATEN MANGGARAI TIMUR' 'KABUPATEN MANOKWARI'
 'KABUPATEN MANOKWARI SELATAN' 'KABUPATEN MAPPI' 'KABUPATEN MAROS'
 'KABUPATEN MAYBRAT' 'KABUPATEN MELAWI' 'KABUPATEN MEMPAWAH'
 'KABUPATEN MERANGIN' 'KABUPATEN MERAUKE' 'KABUPATEN MESUJI'
 'KABUPATEN MIMIKA' 'KABUPATEN MINAHASA' 'KABUPATEN MINAHASA SELATAN'
 'KABUPATEN MINAHASA TENGGARA' 'KABUPATEN MINAHASA UTARA'
 'KABUPATEN MOJOKERTO' 'KABUPATEN MOROWALI' 'KABUPATEN MOROWALI UTARA'
 'KABUPATEN MUARA ENIM' 'KABUPATEN MUARO JAMBI' 'KABUPATEN MUKO MUKO'
 'KABUPATEN MUNA' 'KABUPATEN MUNA BARAT' 'KABUPATEN MURUNG RAYA'
 'KABUPATEN MUSI BANYUASIN' 'KABUPATEN MUSI RAWAS'
 'KABUPATEN MUSI RAWAS UTARA' 'KABUPATEN NABIRE' 'KABUPATEN NAGAN RAYA'
 'KABUPATEN NAGEKEO' 'KABUPATEN NATUNA' 'KABUPATEN NDUGA'
 'KABUPATEN NGADA' 'KABUPATEN NGANJUK' 'KABUPATEN NGAWI' 'KABUPATEN NIAS'
 'KABUPATEN NIAS BARAT' 'KABUPATEN NIAS SELATAN' 'KABUPATEN NIAS UTARA'
 'KABUPATEN NUNUKAN' 'KABUPATEN OGAN ILIR' 'KABUPATEN OGAN KOMERING ILIR'
 'KABUPATEN OGAN KOMERING ULU'
 'KABUPATEN OGAN KOMERING ULU SELATAN (OKU SELATAN)'
 'KABUPATEN OGAN KOMERING ULU TIMUR (OKU TIMUR)' 'KABUPATEN PACITAN'
 'KABUPATEN PADANG LAWAS' 'KABUPATEN PADANG LAWAS UTARA'
 'KABUPATEN PADANG PARIAMAN' 'KABUPATEN PAKPAK BHARAT'
 'KABUPATEN PAMEKASAN' 'KABUPATEN PANDEGLANG' 'KABUPATEN PANGANDARAN'
 'KABUPATEN PANGKAJENE KEPULAUAN' 'KABUPATEN PANIAI'
 'KABUPATEN PARIGI MOUTONG' 'KABUPATEN PASAMAN' 'KABUPATEN PASAMAN BARAT'
 'KABUPATEN PASER' 'KABUPATEN PASURUAN' 'KABUPATEN PATI'
 'KABUPATEN PEGUNUNGAN ARFAK' 'KABUPATEN PEGUNUNGAN BINTANG'
 'KABUPATEN PEKALONGAN' 'KABUPATEN PELALAWAN' 'KABUPATEN PEMALANG'
 'KABUPATEN PENAJAM PASER UTARA' 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'
 'KABUPATEN PESAWARAN' 'KABUPATEN PESISIR BARAT'
 'KABUPATEN PESISIR SELATAN' 'KABUPATEN PIDIE' 'KABUPATEN PIDIE JAYA'
 'KABUPATEN PINRANG' 'KABUPATEN POHUWATO' 'KABUPATEN POLEWALI MANDAR'
 'KABUPATEN PONOROGO' 'KABUPATEN POSO' 'KABUPATEN PRINGSEWU'
 'KABUPATEN PROBOLINGGO' 'KABUPATEN PULANG PISAU'
 'KABUPATEN PULAU MOROTAI' 'KABUPATEN PULAU TALIABU' 'KABUPATEN PUNCAK'
 'KABUPATEN PUNCAK JAYA' 'KABUPATEN PURBALINGGA' 'KABUPATEN PURWAKARTA'
 'KABUPATEN PURWOREJO' 'KABUPATEN RAJA AMPAT' 'KABUPATEN REJANG LEBONG'
 'KABUPATEN REMBANG' 'KABUPATEN ROKAN HILIR' 'KABUPATEN ROKAN HULU'
 'KABUPATEN ROTE NDAO' 'KABUPATEN SABU RAIJUA' 'KABUPATEN SAMBAS'
 'KABUPATEN SAMOSIR' 'KABUPATEN SAMPANG' 'KABUPATEN SANGGAU'
 'KABUPATEN SARMI' 'KABUPATEN SAROLANGUN' 'KABUPATEN SEKADAU'
 'KABUPATEN SELUMA' 'KABUPATEN SEMARANG' 'KABUPATEN SERAM BAGIAN BARAT'
 'KABUPATEN SERAM BAGIAN TIMUR' 'KABUPATEN SERANG'
 'KABUPATEN SERDANG BEDAGAI' 'KABUPATEN SERUYAN' 'KABUPATEN SIAK'
 'KABUPATEN SIDENRENG RAPPANG (SIDRAP)' 'KABUPATEN SIDOARJO'
 'KABUPATEN SIGI' 'KABUPATEN SIJUNJUNG' 'KABUPATEN SIKKA'
 'KABUPATEN SIMALUNGUN' 'KABUPATEN SIMEULUE' 'KABUPATEN SINJAI'
 'KABUPATEN SINTANG' 'KABUPATEN SITUBONDO' 'KABUPATEN SLEMAN'
 'KABUPATEN SOLOK' 'KABUPATEN SOLOK SELATAN' 'KABUPATEN SOPPENG'
 'KABUPATEN SORONG' 'KABUPATEN SORONG SELATAN' 'KABUPATEN SRAGEN'
 'KABUPATEN SUBANG' 'KABUPATEN SUKABUMI' 'KABUPATEN SUKAMARA'
 'KABUPATEN SUKOHARJO' 'KABUPATEN SUMBA BARAT'
 'KABUPATEN SUMBA BARAT DAYA' 'KABUPATEN SUMBA TENGAH'
 'KABUPATEN SUMBA TIMUR' 'KABUPATEN SUMBAWA' 'KABUPATEN SUMBAWA BARAT'
 'KABUPATEN SUMEDANG' 'KABUPATEN SUMENEP' 'KABUPATEN SUPIORI'
 'KABUPATEN TABALONG' 'KABUPATEN TABANAN' 'KABUPATEN TAKALAR'
 'KABUPATEN TAMBRAUW' 'KABUPATEN TANA TIDUNG' 'KABUPATEN TANA TORAJA'
 'KABUPATEN TANAH BUMBU' 'KABUPATEN TANAH DATAR' 'KABUPATEN TANAH LAUT'
 'KABUPATEN TANGERANG' 'KABUPATEN TANGGAMUS'
 'KABUPATEN TANJUNG JABUNG BARAT' 'KABUPATEN TANJUNG JABUNG TIMUR'
 'KABUPATEN TAPANULI SELATAN' 'KABUPATEN TAPANULI TENGAH'
 'KABUPATEN TAPANULI UTARA' 'KABUPATEN TAPIN' 'KABUPATEN TASIKMALAYA'
 'KABUPATEN TEBO' 'KABUPATEN TEGAL' 'KABUPATEN TELUK BINTUNI'
 'KABUPATEN TELUK WONDAMA' 'KABUPATEN TEMANGGUNG'
 'KABUPATEN TIMOR TENGAH SELATAN' 'KABUPATEN TIMOR TENGAH UTARA'
 'KABUPATEN TOBA SAMOSIR' 'KABUPATEN TOJO UNA-UNA' 'KABUPATEN TOLI TOLI'
 'KABUPATEN TOLIKARA' 'KABUPATEN TORAJA UTARA' 'KABUPATEN TRENGGALEK'
 'KABUPATEN TUBAN' 'KABUPATEN TULANG BAWANG'
 'KABUPATEN TULANG BAWANG BARAT' 'KABUPATEN TULUNGAGUNG' 'KABUPATEN WAJO'
 'KABUPATEN WAKATOBI' 'KABUPATEN WAROPEN' 'KABUPATEN WAY KANAN'
 'KABUPATEN WONOGIRI' 'KABUPATEN WONOSOBO' 'KABUPATEN YAHUKIMO'
 'KABUPATEN YALIMO' 'KOTA ADM. JAKARTA BARAT' 'KOTA ADM. JAKARTA PUSAT'
 'KOTA ADM. JAKARTA SELATAN' 'KOTA ADM. JAKARTA TIMUR'
 'KOTA ADM. JAKARTA UTARA' 'KOTA AMBON' 'KOTA BALIKPAPAN'
 'KOTA BANDA ACEH' 'KOTA BANDAR LAMPUNG' 'KOTA BANDUNG' 'KOTA BANJAR'
 'KOTA BANJARBARU' 'KOTA BANJARMASIN' 'KOTA BATAM' 'KOTA BATU'
 'KOTA BAU BAU' 'KOTA BEKASI' 'KOTA BENGKULU' 'KOTA BIMA' 'KOTA BINJAI'
 'KOTA BITUNG' 'KOTA BLITAR' 'KOTA BOGOR' 'KOTA BONTANG'
 'KOTA BUKITTINGGI' 'KOTA CILEGON' 'KOTA CIMAHI' 'KOTA CIREBON'
 'KOTA DENPASAR' 'KOTA DEPOK' 'KOTA DUMAI' 'KOTA GORONTALO'
 'KOTA GUNUNGSITOLI' 'KOTA JAMBI' 'KOTA JAYAPURA' 'KOTA KEDIRI'
 'KOTA KENDARI' 'KOTA KOTAMOBAGU' 'KOTA KUPANG' 'KOTA LANGSA'
 'KOTA LHOKSEUMAWE' 'KOTA LUBUK LINGGAU' 'KOTA MADIUN' 'KOTA MAGELANG'
 'KOTA MAKASSAR' 'KOTA MALANG' 'KOTA MANADO' 'KOTA MATARAM' 'KOTA MEDAN'
 'KOTA METRO' 'KOTA MOJOKERTO' 'KOTA PADANG' 'KOTA PADANG PANJANG'
 'KOTA PADANG SIDEMPUAN' 'KOTA PAGAR ALAM' 'KOTA PALANGKARAYA'
 'KOTA PALEMBANG' 'KOTA PALOPO' 'KOTA PALU' 'KOTA PANGKAL PINANG'
 'KOTA PARE PARE' 'KOTA PARIAMAN' 'KOTA PASURUAN' 'KOTA PAYAKUMBUH'
 'KOTA PEKALONGAN' 'KOTA PEKANBARU' 'KOTA PEMATANGSIANTAR'
 'KOTA PONTIANAK' 'KOTA PRABUMULIH' 'KOTA PROBOLINGGO' 'KOTA SABANG'
 'KOTA SALATIGA' 'KOTA SAMARINDA' 'KOTA SAWAHLUNTO' 'KOTA SEMARANG'
 'KOTA SERANG' 'KOTA SIBOLGA' 'KOTA SINGKAWANG' 'KOTA SOLOK' 'KOTA SORONG'
 'KOTA SUBULUSSALAM' 'KOTA SUKABUMI' 'KOTA SUNGAI PENUH' 'KOTA SURABAYA'
 'KOTA SURAKARTA (SOLO)' 'KOTA TANGERANG' 'KOTA TANGERANG SELATAN'
 'KOTA TANJUNG BALAI' 'KOTA TANJUNG PINANG' 'KOTA TARAKAN'
 'KOTA TASIKMALAYA' 'KOTA TEBING TINGGI' 'KOTA TEGAL' 'KOTA TERNATE'
 'KOTA TIDORE KEPULAUAN' 'KOTA TOMOHON' 'KOTA TUAL' 'KOTA YOGYAKARTA']

In [14]:
# Menghapus kata "Kabupaten" atau "Kota" dari kolom City
df_city_indonesia['City'] = df_city_indonesia['City'].str.replace(r'\b(KABUPATEN|KOTA)\b', '', regex=True).str.strip()

# Menampilkan hasil
print(df_city_indonesia['City'])

0            ACEH BARAT
1       ACEH BARAT DAYA
2            ACEH BESAR
3             ACEH JAYA
4          ACEH SELATAN
             ...
509             TERNATE
510    TIDORE KEPULAUAN
511             TOMOHON
512                TUAL
513          YOGYAKARTA
Name: City, Length: 514, dtype: object

In [15]:
# Menampilkan nilai unik pada kolom City
unique_cities = df_city_indonesia['City'].unique()

# Menampilkan hasil
print(unique_cities)

['ACEH BARAT' 'ACEH BARAT DAYA' 'ACEH BESAR' 'ACEH JAYA' 'ACEH SELATAN'
 'ACEH SINGKIL' 'ACEH TAMIANG' 'ACEH TENGAH' 'ACEH TENGGARA' 'ACEH TIMUR'
 'ACEH UTARA' 'ADM. KEPULAUAN SERIBU' 'AGAM' 'ALOR' 'ASAHAN' 'ASMAT'
 'BADUNG' 'BALANGAN' 'BANDUNG' 'BANDUNG BARAT' 'BANGGAI'
 'BANGGAI KEPULAUAN' 'BANGGAI LAUT' 'BANGKA' 'BANGKA BARAT'
 'BANGKA SELATAN' 'BANGKA TENGAH' 'BANGKALAN' 'BANGLI' 'BANJAR'
 'BANJARNEGARA' 'BANTAENG' 'BANTUL' 'BANYUASIN' 'BANYUMAS' 'BANYUWANGI'
 'BARITO KUALA' 'BARITO SELATAN' 'BARITO TIMUR' 'BARITO UTARA' 'BARRU'
 'BATANG' 'BATANGHARI' 'BATU BARA' 'BEKASI' 'BELITUNG' 'BELITUNG TIMUR'
 'BELU' 'BENER MERIAH' 'BENGKALIS' 'BENGKAYANG' 'BENGKULU SELATAN'
 'BENGKULU TENGAH' 'BENGKULU UTARA' 'BERAU' 'BIAK NUMFOR' 'BIMA' 'BINTAN'
 'BIREUEN' 'BLITAR' 'BLORA' 'BOALEMO' 'BOGOR' 'BOJONEGORO'
 'BOLAANG MONGONDOW' 'BOLAANG MONGONDOW SELATAN' 'BOLAANG MONGONDOW TIMUR'
 'BOLAANG MONGONDOW UTARA' 'BOMBANA' 'BONDOWOSO' 'BONE' 'BONE BOLANGO'
 'BOVEN DIGOEL' 'BOYOLALI' 'BREBES' 'BULELENG' 'BULUKUMBA' 'BULUNGAN'
 'BUNGO' 'BUOL' 'BURU' 'BURU SELATAN' 'BUTON' 'BUTON SELATAN'
 'BUTON TENGAH' 'BUTON UTARA' 'CIAMIS' 'CIANJUR' 'CILACAP' 'CIREBON'
 'DAIRI' 'DEIYAI (DELIYAI)' 'DELI SERDANG' 'DEMAK' 'DHARMASRAYA' 'DOGIYAI'
 'DOMPU' 'DONGGALA' 'EMPAT LAWANG' 'ENDE' 'ENREKANG' 'FAKFAK'
 'FLORES TIMUR' 'GARUT' 'GAYO LUES' 'GIANYAR' 'GORONTALO'
 'GORONTALO UTARA' 'GOWA' 'GRESIK' 'GROBOGAN' 'GUNUNG KIDUL' 'GUNUNG MAS'
 'HALMAHERA BARAT' 'HALMAHERA SELATAN' 'HALMAHERA TENGAH'
 'HALMAHERA TIMUR' 'HALMAHERA UTARA' 'HULU SUNGAI SELATAN'
 'HULU SUNGAI TENGAH' 'HULU SUNGAI UTARA' 'HUMBANG HASUNDUTAN'
 'INDRAGIRI HILIR' 'INDRAGIRI HULU' 'INDRAMAYU' 'INTAN JAYA' 'JAYAPURA'
 'JAYAWIJAYA' 'JEMBER' 'JEMBRANA' 'JENEPONTO' 'JEPARA' 'JOMBANG' 'KAIMANA'
 'KAMPAR' 'KAPUAS' 'KAPUAS HULU' 'KARANGANYAR' 'KARANGASEM' 'KARAWANG'
 'KARIMUN' 'KARO' 'KATINGAN' 'KAUR' 'KAYONG UTARA' 'KEBUMEN' 'KEDIRI'
 'KEEROM' 'KENDAL' 'KEPAHIANG' 'KEPULAUAN ANAMBAS' 'KEPULAUAN ARU'
 'KEPULAUAN MENTAWAI' 'KEPULAUAN MERANTI' 'KEPULAUAN SANGIHE'
 'KEPULAUAN SELAYAR' 'KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)'
 'KEPULAUAN SULA' 'KEPULAUAN TALAUD' 'KEPULAUAN YAPEN (YAPEN WAROPEN)'
 'KERINCI' 'KETAPANG' 'KLATEN' 'KLUNGKUNG' 'KOLAKA' 'KOLAKA TIMUR'
 'KOLAKA UTARA' 'KONAWE' 'KONAWE KEPULAUAN' 'KONAWE SELATAN'
 'KONAWE UTARA' 'KOTABARU' 'KOTAWARINGIN BARAT' 'KOTAWARINGIN TIMUR'
 'KUANTAN SINGINGI' 'KUBU RAYA' 'KUDUS' 'KULON PROGO' 'KUNINGAN' 'KUPANG'
 'KUTAI BARAT' 'KUTAI KARTANEGARA' 'KUTAI TIMUR' 'LABUHANBATU'
 'LABUHANBATU SELATAN' 'LABUHANBATU UTARA' 'LAHAT' 'LAMANDAU' 'LAMONGAN'
 'LAMPUNG BARAT' 'LAMPUNG SELATAN' 'LAMPUNG TENGAH' 'LAMPUNG TIMUR'
 'LAMPUNG UTARA' 'LANDAK' 'LANGKAT' 'LANNY JAYA' 'LEBAK' 'LEBONG'
 'LEMBATA' 'LIMA PULUH' 'LINGGA' 'LOMBOK BARAT' 'LOMBOK TENGAH'
 'LOMBOK TIMUR' 'LOMBOK UTARA' 'LUMAJANG' 'LUWU' 'LUWU TIMUR' 'LUWU UTARA'
 'MADIUN' 'MAGELANG' 'MAGETAN' 'MAHAKAM ULU' 'MAJALENGKA' 'MAJENE'
 'MALAKA' 'MALANG' 'MALINAU' 'MALUKU BARAT DAYA' 'MALUKU TENGAH'
 'MALUKU TENGGARA' 'MALUKU TENGGARA BARAT' 'MAMASA' 'MAMBERAMO RAYA'
 'MAMBERAMO TENGAH' 'MAMUJU' 'MAMUJU TENGAH' 'MAMUJU UTARA'
 'MANDAILING NATAL' 'MANGGARAI' 'MANGGARAI BARAT' 'MANGGARAI TIMUR'
 'MANOKWARI' 'MANOKWARI SELATAN' 'MAPPI' 'MAROS' 'MAYBRAT' 'MELAWI'
 'MEMPAWAH' 'MERANGIN' 'MERAUKE' 'MESUJI' 'MIMIKA' 'MINAHASA'
 'MINAHASA SELATAN' 'MINAHASA TENGGARA' 'MINAHASA UTARA' 'MOJOKERTO'
 'MOROWALI' 'MOROWALI UTARA' 'MUARA ENIM' 'MUARO JAMBI' 'MUKO MUKO' 'MUNA'
 'MUNA BARAT' 'MURUNG RAYA' 'MUSI BANYUASIN' 'MUSI RAWAS'
 'MUSI RAWAS UTARA' 'NABIRE' 'NAGAN RAYA' 'NAGEKEO' 'NATUNA' 'NDUGA'
 'NGADA' 'NGANJUK' 'NGAWI' 'NIAS' 'NIAS BARAT' 'NIAS SELATAN' 'NIAS UTARA'
 'NUNUKAN' 'OGAN ILIR' 'OGAN KOMERING ILIR' 'OGAN KOMERING ULU'
 'OGAN KOMERING ULU SELATAN (OKU SELATAN)'
 'OGAN KOMERING ULU TIMUR (OKU TIMUR)' 'PACITAN' 'PADANG LAWAS'
 'PADANG LAWAS UTARA' 'PADANG PARIAMAN' 'PAKPAK BHARAT' 'PAMEKASAN'
 'PANDEGLANG' 'PANGANDARAN' 'PANGKAJENE KEPULAUAN' 'PANIAI'
 'PARIGI MOUTONG' 'PASAMAN' 'PASAMAN BARAT' 'PASER' 'PASURUAN' 'PATI'
 'PEGUNUNGAN ARFAK' 'PEGUNUNGAN BINTANG' 'PEKALONGAN' 'PELALAWAN'
 'PEMALANG' 'PENAJAM PASER UTARA' 'PENUKAL ABAB LEMATANG ILIR' 'PESAWARAN'
 'PESISIR BARAT' 'PESISIR SELATAN' 'PIDIE' 'PIDIE JAYA' 'PINRANG'
 'POHUWATO' 'POLEWALI MANDAR' 'PONOROGO' 'POSO' 'PRINGSEWU' 'PROBOLINGGO'
 'PULANG PISAU' 'PULAU MOROTAI' 'PULAU TALIABU' 'PUNCAK' 'PUNCAK JAYA'
 'PURBALINGGA' 'PURWAKARTA' 'PURWOREJO' 'RAJA AMPAT' 'REJANG LEBONG'
 'REMBANG' 'ROKAN HILIR' 'ROKAN HULU' 'ROTE NDAO' 'SABU RAIJUA' 'SAMBAS'
 'SAMOSIR' 'SAMPANG' 'SANGGAU' 'SARMI' 'SAROLANGUN' 'SEKADAU' 'SELUMA'
 'SEMARANG' 'SERAM BAGIAN BARAT' 'SERAM BAGIAN TIMUR' 'SERANG'
 'SERDANG BEDAGAI' 'SERUYAN' 'SIAK' 'SIDENRENG RAPPANG (SIDRAP)'
 'SIDOARJO' 'SIGI' 'SIJUNJUNG' 'SIKKA' 'SIMALUNGUN' 'SIMEULUE' 'SINJAI'
 'SINTANG' 'SITUBONDO' 'SLEMAN' 'SOLOK' 'SOLOK SELATAN' 'SOPPENG' 'SORONG'
 'SORONG SELATAN' 'SRAGEN' 'SUBANG' 'SUKABUMI' 'SUKAMARA' 'SUKOHARJO'
 'SUMBA BARAT' 'SUMBA BARAT DAYA' 'SUMBA TENGAH' 'SUMBA TIMUR' 'SUMBAWA'
 'SUMBAWA BARAT' 'SUMEDANG' 'SUMENEP' 'SUPIORI' 'TABALONG' 'TABANAN'
 'TAKALAR' 'TAMBRAUW' 'TANA TIDUNG' 'TANA TORAJA' 'TANAH BUMBU'
 'TANAH DATAR' 'TANAH LAUT' 'TANGERANG' 'TANGGAMUS' 'TANJUNG JABUNG BARAT'
 'TANJUNG JABUNG TIMUR' 'TAPANULI SELATAN' 'TAPANULI TENGAH'
 'TAPANULI UTARA' 'TAPIN' 'TASIKMALAYA' 'TEBO' 'TEGAL' 'TELUK BINTUNI'
 'TELUK WONDAMA' 'TEMANGGUNG' 'TIMOR TENGAH SELATAN' 'TIMOR TENGAH UTARA'
 'TOBA SAMOSIR' 'TOJO UNA-UNA' 'TOLI TOLI' 'TOLIKARA' 'TORAJA UTARA'
 'TRENGGALEK' 'TUBAN' 'TULANG BAWANG' 'TULANG BAWANG BARAT' 'TULUNGAGUNG'
 'WAJO' 'WAKATOBI' 'WAROPEN' 'WAY KANAN' 'WONOGIRI' 'WONOSOBO' 'YAHUKIMO'
 'YALIMO' 'ADM. JAKARTA BARAT' 'ADM. JAKARTA PUSAT' 'ADM. JAKARTA SELATAN'
 'ADM. JAKARTA TIMUR' 'ADM. JAKARTA UTARA' 'AMBON' 'BALIKPAPAN'
 'BANDA ACEH' 'BANDAR LAMPUNG' 'BANJARBARU' 'BANJARMASIN' 'BATAM' 'BATU'
 'BAU BAU' 'BENGKULU' 'BINJAI' 'BITUNG' 'BONTANG' 'BUKITTINGGI' 'CILEGON'
 'CIMAHI' 'DENPASAR' 'DEPOK' 'DUMAI' 'GUNUNGSITOLI' 'JAMBI' 'KENDARI'
 'KOTAMOBAGU' 'LANGSA' 'LHOKSEUMAWE' 'LUBUK LINGGAU' 'MAKASSAR' 'MANADO'
 'MATARAM' 'MEDAN' 'METRO' 'PADANG' 'PADANG PANJANG' 'PADANG SIDEMPUAN'
 'PAGAR ALAM' 'PALANGKARAYA' 'PALEMBANG' 'PALOPO' 'PALU' 'PANGKAL PINANG'
 'PARE PARE' 'PARIAMAN' 'PAYAKUMBUH' 'PEKANBARU' 'PEMATANGSIANTAR'
 'PONTIANAK' 'PRABUMULIH' 'SABANG' 'SALATIGA' 'SAMARINDA' 'SAWAHLUNTO'
 'SIBOLGA' 'SINGKAWANG' 'SUBULUSSALAM' 'SUNGAI PENUH' 'SURABAYA'
 'SURAKARTA (SOLO)' 'TANGERANG SELATAN' 'TANJUNG BALAI' 'TANJUNG PINANG'
 'TARAKAN' 'TEBING TINGGI' 'TERNATE' 'TIDORE KEPULAUAN' 'TOMOHON' 'TUAL'
 'YOGYAKARTA']

In [16]:
# Menghapus kata "ADM." dari kolom City
df_city_indonesia['City'] = df_city_indonesia['City'].str.replace('ADM.', '', regex=False).str.strip()

In [17]:
df_city_indonesia['City'] = df_city_indonesia['City'].replace({
    'TOJO UNA-UNA': 'TOJO UNA UNA',
    'OGAN KOMERING ULU SELATAN (OKU SELATAN)': 'OKU SELATAN',
    'OGAN KOMERING ULU TIMUR (OKU TIMUR)': 'OKU TIMUR',
    'SIDENRENG RAPPANG (SIDRAP)': 'SIDENRENG RAPPANG',
    'SURAKARTA (SOLO)': 'SURAKARTA',
    'LIMA PULUH': 'LIMA PULUH KOTA',
    'KUTAI KARTANEGARA': 'KUTAI KERTANEGARA',
    'FAKFAK': 'FAK FAK',
    'KEPULAUAN YAPEN (YAPEN WAROPEN)': 'KEPULAUAN YAPEN',
    'LABUHANBATU SELATAN': 'LABUHAN BATU SELATAN',
    'LABUHANBATU UTARA': 'LABUHAN BATU UTARA',
    'LABUHANBATU': 'LABUHAN BATU',
    'POHUWATO': 'PAHUWATO',
    'PANGKAJENE KEPULAUAN': 'PANGKAJENE'
})

In [18]:
df_city_indonesia['City'] = df_city_indonesia['City'].replace({
    'KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)': 'KEPULAUAN SIAU TAGULANDANG BIARO'
})

In [19]:
# Menampilkan nilai unik pada kolom City
unique_cities = df_city_indonesia['City'].unique()

# Menampilkan hasil
print(unique_cities)

['ACEH BARAT' 'ACEH BARAT DAYA' 'ACEH BESAR' 'ACEH JAYA' 'ACEH SELATAN'
 'ACEH SINGKIL' 'ACEH TAMIANG' 'ACEH TENGAH' 'ACEH TENGGARA' 'ACEH TIMUR'
 'ACEH UTARA' 'KEPULAUAN SERIBU' 'AGAM' 'ALOR' 'ASAHAN' 'ASMAT' 'BADUNG'
 'BALANGAN' 'BANDUNG' 'BANDUNG BARAT' 'BANGGAI' 'BANGGAI KEPULAUAN'
 'BANGGAI LAUT' 'BANGKA' 'BANGKA BARAT' 'BANGKA SELATAN' 'BANGKA TENGAH'
 'BANGKALAN' 'BANGLI' 'BANJAR' 'BANJARNEGARA' 'BANTAENG' 'BANTUL'
 'BANYUASIN' 'BANYUMAS' 'BANYUWANGI' 'BARITO KUALA' 'BARITO SELATAN'
 'BARITO TIMUR' 'BARITO UTARA' 'BARRU' 'BATANG' 'BATANGHARI' 'BATU BARA'
 'BEKASI' 'BELITUNG' 'BELITUNG TIMUR' 'BELU' 'BENER MERIAH' 'BENGKALIS'
 'BENGKAYANG' 'BENGKULU SELATAN' 'BENGKULU TENGAH' 'BENGKULU UTARA'
 'BERAU' 'BIAK NUMFOR' 'BIMA' 'BINTAN' 'BIREUEN' 'BLITAR' 'BLORA'
 'BOALEMO' 'BOGOR' 'BOJONEGORO' 'BOLAANG MONGONDOW'
 'BOLAANG MONGONDOW SELATAN' 'BOLAANG MONGONDOW TIMUR'
 'BOLAANG MONGONDOW UTARA' 'BOMBANA' 'BONDOWOSO' 'BONE' 'BONE BOLANGO'
 'BOVEN DIGOEL' 'BOYOLALI' 'BREBES' 'BULELENG' 'BULUKUMBA' 'BULUNGAN'
 'BUNGO' 'BUOL' 'BURU' 'BURU SELATAN' 'BUTON' 'BUTON SELATAN'
 'BUTON TENGAH' 'BUTON UTARA' 'CIAMIS' 'CIANJUR' 'CILACAP' 'CIREBON'
 'DAIRI' 'DEIYAI (DELIYAI)' 'DELI SERDANG' 'DEMAK' 'DHARMASRAYA' 'DOGIYAI'
 'DOMPU' 'DONGGALA' 'EMPAT LAWANG' 'ENDE' 'ENREKANG' 'FAK FAK'
 'FLORES TIMUR' 'GARUT' 'GAYO LUES' 'GIANYAR' 'GORONTALO'
 'GORONTALO UTARA' 'GOWA' 'GRESIK' 'GROBOGAN' 'GUNUNG KIDUL' 'GUNUNG MAS'
 'HALMAHERA BARAT' 'HALMAHERA SELATAN' 'HALMAHERA TENGAH'
 'HALMAHERA TIMUR' 'HALMAHERA UTARA' 'HULU SUNGAI SELATAN'
 'HULU SUNGAI TENGAH' 'HULU SUNGAI UTARA' 'HUMBANG HASUNDUTAN'
 'INDRAGIRI HILIR' 'INDRAGIRI HULU' 'INDRAMAYU' 'INTAN JAYA' 'JAYAPURA'
 'JAYAWIJAYA' 'JEMBER' 'JEMBRANA' 'JENEPONTO' 'JEPARA' 'JOMBANG' 'KAIMANA'
 'KAMPAR' 'KAPUAS' 'KAPUAS HULU' 'KARANGANYAR' 'KARANGASEM' 'KARAWANG'
 'KARIMUN' 'KARO' 'KATINGAN' 'KAUR' 'KAYONG UTARA' 'KEBUMEN' 'KEDIRI'
 'KEEROM' 'KENDAL' 'KEPAHIANG' 'KEPULAUAN ANAMBAS' 'KEPULAUAN ARU'
 'KEPULAUAN MENTAWAI' 'KEPULAUAN MERANTI' 'KEPULAUAN SANGIHE'
 'KEPULAUAN SELAYAR' 'KEPULAUAN SIAU TAGULANDANG BIARO' 'KEPULAUAN SULA'
 'KEPULAUAN TALAUD' 'KEPULAUAN YAPEN' 'KERINCI' 'KETAPANG' 'KLATEN'
 'KLUNGKUNG' 'KOLAKA' 'KOLAKA TIMUR' 'KOLAKA UTARA' 'KONAWE'
 'KONAWE KEPULAUAN' 'KONAWE SELATAN' 'KONAWE UTARA' 'KOTABARU'
 'KOTAWARINGIN BARAT' 'KOTAWARINGIN TIMUR' 'KUANTAN SINGINGI' 'KUBU RAYA'
 'KUDUS' 'KULON PROGO' 'KUNINGAN' 'KUPANG' 'KUTAI BARAT'
 'KUTAI KERTANEGARA' 'KUTAI TIMUR' 'LABUHAN BATU' 'LABUHAN BATU SELATAN'
 'LABUHAN BATU UTARA' 'LAHAT' 'LAMANDAU' 'LAMONGAN' 'LAMPUNG BARAT'
 'LAMPUNG SELATAN' 'LAMPUNG TENGAH' 'LAMPUNG TIMUR' 'LAMPUNG UTARA'
 'LANDAK' 'LANGKAT' 'LANNY JAYA' 'LEBAK' 'LEBONG' 'LEMBATA'
 'LIMA PULUH KOTA' 'LINGGA' 'LOMBOK BARAT' 'LOMBOK TENGAH' 'LOMBOK TIMUR'
 'LOMBOK UTARA' 'LUMAJANG' 'LUWU' 'LUWU TIMUR' 'LUWU UTARA' 'MADIUN'
 'MAGELANG' 'MAGETAN' 'MAHAKAM ULU' 'MAJALENGKA' 'MAJENE' 'MALAKA'
 'MALANG' 'MALINAU' 'MALUKU BARAT DAYA' 'MALUKU TENGAH' 'MALUKU TENGGARA'
 'MALUKU TENGGARA BARAT' 'MAMASA' 'MAMBERAMO RAYA' 'MAMBERAMO TENGAH'
 'MAMUJU' 'MAMUJU TENGAH' 'MAMUJU UTARA' 'MANDAILING NATAL' 'MANGGARAI'
 'MANGGARAI BARAT' 'MANGGARAI TIMUR' 'MANOKWARI' 'MANOKWARI SELATAN'
 'MAPPI' 'MAROS' 'MAYBRAT' 'MELAWI' 'MEMPAWAH' 'MERANGIN' 'MERAUKE'
 'MESUJI' 'MIMIKA' 'MINAHASA' 'MINAHASA SELATAN' 'MINAHASA TENGGARA'
 'MINAHASA UTARA' 'MOJOKERTO' 'MOROWALI' 'MOROWALI UTARA' 'MUARA ENIM'
 'MUARO JAMBI' 'MUKO MUKO' 'MUNA' 'MUNA BARAT' 'MURUNG RAYA'
 'MUSI BANYUASIN' 'MUSI RAWAS' 'MUSI RAWAS UTARA' 'NABIRE' 'NAGAN RAYA'
 'NAGEKEO' 'NATUNA' 'NDUGA' 'NGADA' 'NGANJUK' 'NGAWI' 'NIAS' 'NIAS BARAT'
 'NIAS SELATAN' 'NIAS UTARA' 'NUNUKAN' 'OGAN ILIR' 'OGAN KOMERING ILIR'
 'OGAN KOMERING ULU' 'OKU SELATAN' 'OKU TIMUR' 'PACITAN' 'PADANG LAWAS'
 'PADANG LAWAS UTARA' 'PADANG PARIAMAN' 'PAKPAK BHARAT' 'PAMEKASAN'
 'PANDEGLANG' 'PANGANDARAN' 'PANGKAJENE' 'PANIAI' 'PARIGI MOUTONG'
 'PASAMAN' 'PASAMAN BARAT' 'PASER' 'PASURUAN' 'PATI' 'PEGUNUNGAN ARFAK'
 'PEGUNUNGAN BINTANG' 'PEKALONGAN' 'PELALAWAN' 'PEMALANG'
 'PENAJAM PASER UTARA' 'PENUKAL ABAB LEMATANG ILIR' 'PESAWARAN'
 'PESISIR BARAT' 'PESISIR SELATAN' 'PIDIE' 'PIDIE JAYA' 'PINRANG'
 'PAHUWATO' 'POLEWALI MANDAR' 'PONOROGO' 'POSO' 'PRINGSEWU' 'PROBOLINGGO'
 'PULANG PISAU' 'PULAU MOROTAI' 'PULAU TALIABU' 'PUNCAK' 'PUNCAK JAYA'
 'PURBALINGGA' 'PURWAKARTA' 'PURWOREJO' 'RAJA AMPAT' 'REJANG LEBONG'
 'REMBANG' 'ROKAN HILIR' 'ROKAN HULU' 'ROTE NDAO' 'SABU RAIJUA' 'SAMBAS'
 'SAMOSIR' 'SAMPANG' 'SANGGAU' 'SARMI' 'SAROLANGUN' 'SEKADAU' 'SELUMA'
 'SEMARANG' 'SERAM BAGIAN BARAT' 'SERAM BAGIAN TIMUR' 'SERANG'
 'SERDANG BEDAGAI' 'SERUYAN' 'SIAK' 'SIDENRENG RAPPANG' 'SIDOARJO' 'SIGI'
 'SIJUNJUNG' 'SIKKA' 'SIMALUNGUN' 'SIMEULUE' 'SINJAI' 'SINTANG'
 'SITUBONDO' 'SLEMAN' 'SOLOK' 'SOLOK SELATAN' 'SOPPENG' 'SORONG'
 'SORONG SELATAN' 'SRAGEN' 'SUBANG' 'SUKABUMI' 'SUKAMARA' 'SUKOHARJO'
 'SUMBA BARAT' 'SUMBA BARAT DAYA' 'SUMBA TENGAH' 'SUMBA TIMUR' 'SUMBAWA'
 'SUMBAWA BARAT' 'SUMEDANG' 'SUMENEP' 'SUPIORI' 'TABALONG' 'TABANAN'
 'TAKALAR' 'TAMBRAUW' 'TANA TIDUNG' 'TANA TORAJA' 'TANAH BUMBU'
 'TANAH DATAR' 'TANAH LAUT' 'TANGERANG' 'TANGGAMUS' 'TANJUNG JABUNG BARAT'
 'TANJUNG JABUNG TIMUR' 'TAPANULI SELATAN' 'TAPANULI TENGAH'
 'TAPANULI UTARA' 'TAPIN' 'TASIKMALAYA' 'TEBO' 'TEGAL' 'TELUK BINTUNI'
 'TELUK WONDAMA' 'TEMANGGUNG' 'TIMOR TENGAH SELATAN' 'TIMOR TENGAH UTARA'
 'TOBA SAMOSIR' 'TOJO UNA UNA' 'TOLI TOLI' 'TOLIKARA' 'TORAJA UTARA'
 'TRENGGALEK' 'TUBAN' 'TULANG BAWANG' 'TULANG BAWANG BARAT' 'TULUNGAGUNG'
 'WAJO' 'WAKATOBI' 'WAROPEN' 'WAY KANAN' 'WONOGIRI' 'WONOSOBO' 'YAHUKIMO'
 'YALIMO' 'JAKARTA BARAT' 'JAKARTA PUSAT' 'JAKARTA SELATAN'
 'JAKARTA TIMUR' 'JAKARTA UTARA' 'AMBON' 'BALIKPAPAN' 'BANDA ACEH'
 'BANDAR LAMPUNG' 'BANJARBARU' 'BANJARMASIN' 'BATAM' 'BATU' 'BAU BAU'
 'BENGKULU' 'BINJAI' 'BITUNG' 'BONTANG' 'BUKITTINGGI' 'CILEGON' 'CIMAHI'
 'DENPASAR' 'DEPOK' 'DUMAI' 'GUNUNGSITOLI' 'JAMBI' 'KENDARI' 'KOTAMOBAGU'
 'LANGSA' 'LHOKSEUMAWE' 'LUBUK LINGGAU' 'MAKASSAR' 'MANADO' 'MATARAM'
 'MEDAN' 'METRO' 'PADANG' 'PADANG PANJANG' 'PADANG SIDEMPUAN' 'PAGAR ALAM'
 'PALANGKARAYA' 'PALEMBANG' 'PALOPO' 'PALU' 'PANGKAL PINANG' 'PARE PARE'
 'PARIAMAN' 'PAYAKUMBUH' 'PEKANBARU' 'PEMATANGSIANTAR' 'PONTIANAK'
 'PRABUMULIH' 'SABANG' 'SALATIGA' 'SAMARINDA' 'SAWAHLUNTO' 'SIBOLGA'
 'SINGKAWANG' 'SUBULUSSALAM' 'SUNGAI PENUH' 'SURABAYA' 'SURAKARTA'
 'TANGERANG SELATAN' 'TANJUNG BALAI' 'TANJUNG PINANG' 'TARAKAN'
 'TEBING TINGGI' 'TERNATE' 'TIDORE KEPULAUAN' 'TOMOHON' 'TUAL'
 'YOGYAKARTA']

In [20]:
# Menampilkan nilai unik pada kolom Alamat4
unique_alamat4 = df_assessment['Alamat4'].unique()

# Menampilkan hasil
print(unique_alamat4)

['BENGKULU UTARA' 'LABUHANBATU UTARA' 'AMBON, KOTA' 'MALUKU TENGAH'
 'TOJO UNA UNA' 'MINAHASA UTARA' 'WAY KANAN' 'BANDAR LAMPUNG, KOTA'
 'BONDOWOSO' 'BENGKAYANG' 'MOROWALI' 'BENGKULU, KOTA' 'BIMA'
 'BITUNG, KOTA' 'BANJARBARU, KOTA' 'KAMPAR' 'MERANGIN' 'BEKASI, KOTA'
 'BLORA' 'TOBA SAMOSIR' 'BULUKUMBA' 'TANAH BUMBU' 'BENGKALIS'
 'ACEH TAMIANG' 'BANDA ACEH, KOTA' 'LANGKAT' 'BINJAI, KOTA'
 'ACEH BARAT DAYA' 'BALIKPAPAN, KOTA' 'BINTAN' 'BATANG' 'BATAM, KOTA'
 'BATU, KOTA' 'BANYUWANGI' 'BOGOR' 'TANGERANG' 'CIANJUR'
 'JAKARTA TIMUR, KOTA' 'BEKASI' 'LEBAK' 'CILACAP' 'CIMAHI, KOTA' 'CIAMIS'
 'DONGGALA' 'PALU, KOTA' 'HUMBANG HASUNDUTAN' 'DEPOK, KOTA' 'DOMPU'
 'SERAM BAGIAN BARAT' 'SERAM BAGIAN TIMUR' 'ENREKANG' 'PESAWARAN'
 'GIANYAR' 'LAMPUNG TENGAH' 'PADANG LAWAS UTARA' 'LOMBOK BARAT' 'GARUT'
 'GRESIK' 'GUNUNGSITOLI, KOTA' 'NIAS' 'OGAN ILIR' 'INDRAMAYU' 'JAYAPURA'
 'JOMBANG' 'JAMBI, KOTA' 'JEMBER' 'JENEPONTO' 'OGAN KOMERING ILIR' 'KARO'
 'KEBUMEN' 'KOTABARU' 'KENDARI, KOTA' 'BUTON' 'BAU BAU, KOTA' 'MUNA'
 'KONAWE' 'KENDAL' 'KEDIRI, KOTA' 'KEDIRI' 'MAPPI' 'ASAHAN' 'KOLAKA'
 'BANDUNG, KOTA' 'BANDUNG' 'KUNINGAN' 'BLITAR' 'KUPANG' 'MALANG'
 'KARANGASEM' 'ACEH TIMUR' 'PROBOLINGGO' 'PONOROGO' 'KOTAMOBAGU, KOTA'
 'ACEH TENGGARA' 'KARAWANG' 'TANGERANG SELATAN, KOTA'
 'JAKARTA SELATAN, KOTA' 'DELI SERDANG' 'PASAMAN' 'NIAS BARAT' 'LAHAT'
 'LAMPUNG BARAT' 'BOLAANG MONGONDOW' 'LAMONGAN' 'LUMAJANG' 'BATU BARA'
 'FLORES TIMUR' 'ACEH UTARA' 'LHOKSEUMAWE, KOTA' 'NIAS UTARA' 'BANGGAI'
 'TAPANULI UTARA' 'HALMAHERA TIMUR' 'MADIUN' 'MADIUN, KOTA' 'TANA TORAJA'
 'MAMUJU' 'MUSI RAWAS' 'BATANGHARI' 'MEDAN, KOTA' 'MAGETAN' 'MOJOKERTO'
 'MAJENE' 'MAGELANG' 'MAKASSAR, KOTA' 'LUWU TIMUR' 'OKU TIMUR' 'BUNGO'
 'OKU SELATAN' 'MUARA ENIM' 'MAROS' 'TEBO' 'MESUJI' 'BANGKA BARAT'
 'MATARAM, KOTA' 'BARITO UTARA' 'NGAWI' 'NGANJUK' 'BURU' 'BANDUNG BARAT'
 'PADANG PARIAMAN' 'PEKANBARU, KOTA' 'KOTAWARINGIN BARAT' 'PANDEGLANG'
 'PINRANG' 'BANYUASIN' 'PANGKAJENE KEPULAUAN' 'PELALAWAN'
 'PALEMBANG, KOTA' 'PALANGKARAYA, KOTA' 'PALOPO, KOTA' 'LUWU'
 'POLEWALI MANDAR' 'PEMALANG' 'PEMATANGSIANTAR, KOTA' 'SIMALUNGUN'
 'PARE PARE, KOTA' 'PARIGI MOUTONG' 'ROKAN HULU' 'TAPANULI SELATAN'
 'PASURUAN' 'PATI' 'KAPUAS HULU' 'GROBOGAN' 'PURWAKARTA' 'PURWOREJO'
 'BANYUMAS' 'MANDAILING NATAL' 'LABUHANBATU' 'INDRAGIRI HULU'
 'MINAHASA TENGGARA' 'SANGGAU' 'SIAK' 'TAPANULI TENGAH' 'PADANG LAWAS'
 'SUKABUMI' 'CIREBON' 'SUMBAWA' 'SURABAYA, KOTA' 'SIDOARJO' 'DAIRI'
 'LAMPUNG TIMUR' 'LAMPUNG UTARA' 'SIDENRENG RAPPANG' 'SIGI' 'GOWA'
 'SRAGEN' 'BULELENG' 'KUTAI TIMUR' 'SITUBONDO' 'WAJO' 'SUKOHARJO'
 'SURAKARTA, KOTA' 'MUSI BANYUASIN' 'SEMARANG, KOTA' 'SAMARINDA, KOTA'
 'SIMEULUE' 'SUBANG' 'SINJAI' 'KEPULAUAN SULA' 'MUARO JAMBI'
 'TIMOR TENGAH SELATAN' 'TASIKMALAYA' 'PASAMAN BARAT' 'KOTAWARINGIN TIMUR'
 'SERANG' 'SERDANG BEDAGAI' 'LIMA PULUH KOTA' 'SAROLANGUN' 'KLUNGKUNG'
 'LANGSA, KOTA' 'SINTANG' 'BONE BOLANGO' 'TABANAN' 'EMPAT LAWANG'
 'INDRAGIRI HILIR' 'KARIMUN' 'BANGKA SELATAN' 'TIDORE KEPULAUAN, KOTA'
 'KEPULAUAN SANGIHE' 'TABALONG' 'JAKARTA UTARA, KOTA' 'TAKALAR'
 'ACEH TENGAH' 'NIAS SELATAN' 'TOLI TOLI' 'KUANTAN SINGINGI' 'BOALEMO'
 'MINAHASA' 'KUTAI KERTANEGARA' 'KEPULAUAN MERANTI' 'ACEH SELATAN'
 'TUAL, KOTA' 'TULANG BAWANG BARAT' 'ROKAN HILIR' 'KONAWE UTARA'
 'SUMBA TIMUR' 'WONOGIRI' 'GUNUNG KIDUL' 'SOPPENG' 'BONE' 'KONAWE SELATAN'
 'BENGKULU TENGAH' 'MINAHASA SELATAN' 'BALANGAN' 'HULU SUNGAI UTARA'
 'SOLOK' 'BELU' 'BANTAENG' 'BARRU' 'BREBES' 'KEPULAUAN SELAYAR'
 'BOGOR, KOTA' 'KAUR' 'BENGKULU SELATAN' 'BIMA, KOTA' 'BIREUEN' 'BANJAR'
 'BANJARMASIN, KOTA' 'BOJONEGORO' 'BOLAANG MONGONDOW SELATAN'
 'BUTON UTARA' 'BANJARNEGARA' 'BARITO SELATAN' 'MANGGARAI TIMUR'
 'BOLAANG MONGONDOW UTARA' 'OGAN KOMERING ULU' 'BANTUL' 'BUOL' 'BOYOLALI'
 'ACEH JAYA' 'CIREBON, KOTA' 'REJANG LEBONG' 'DEMAK' 'DENPASAR, KOTA'
 'FAK FAK' 'JAKARTA BARAT, KOTA' 'TULANG BAWANG' 'GORONTALO, KOTA'
 'GORONTALO' 'JAYAPURA, KOTA' 'JEPARA' 'ACEH BESAR' 'BOMBANA'
 'KOLAKA UTARA' 'KUDUS' 'TIMOR TENGAH UTARA' 'HULU SUNGAI SELATAN'
 'PEKALONGAN' 'LAMPUNG SELATAN' 'KAPUAS' 'KLATEN' 'SERUYAN'
 'TANJUNG JABUNG BARAT' 'TANGGAMUS' 'KUPANG, KOTA' 'KEPAHIANG'
 'LABUHANBATU SELATAN' 'KETAPANG' 'GORONTALO UTARA' 'HALMAHERA SELATAN'
 'AGAM' 'MANGGARAI BARAT' 'ACEH BARAT' 'KEPULAUAN TALAUD' 'BADUNG'
 'MAJALENGKA' 'MUKO MUKO' 'MALANG, KOTA' 'MALINAU' 'MANADO, KOTA'
 'MANOKWARI' 'BARITO KUALA' 'SIJUNJUNG' 'PIDIE JAYA' 'LUWU UTARA'
 'TANJUNG JABUNG TIMUR' 'PULAU MOROTAI' 'LANDAK' 'JEMBRANA' 'LAMANDAU'
 'MELAWI' 'NUNUKAN' 'PARIAMAN, KOTA' 'PADANG, KOTA' 'PURBALINGGA'
 'PROBOLINGGO, KOTA' 'PACITAN' 'PADANG PANJANG, KOTA' 'PAGAR ALAM, KOTA'
 'PANGKAL PINANG, KOTA' 'MAMUJU UTARA' 'TANAH LAUT' 'DHARMASRAYA'
 'PAMEKASAN' 'PENAJAM PASER UTARA' 'PESISIR SELATAN' 'PULANG PISAU'
 'MURUNG RAYA' 'SAMOSIR' 'PRINGSEWU' 'POSO' 'PADANG SIDEMPUAN, KOTA'
 'PONTIANAK, KOTA' 'LOMBOK TENGAH' 'PAYAKUMBUH, KOTA' 'NATUNA' 'REMBANG'
 'TAPIN' 'MANGGARAI' 'TORAJA UTARA' 'KUTAI BARAT' 'SEKADAU' 'LOMBOK TIMUR'
 'PIDIE' 'GAYO LUES' 'BANGKA' 'NAGAN RAYA' 'BANGGAI KEPULAUAN'
 'SALATIGA, KOTA' 'SUMEDANG' 'SLEMAN' 'SUMENEP' 'SAMPANG' 'KUBU RAYA'
 'SERANG, KOTA' 'KEPULAUAN YAPEN' 'BENER MERIAH' 'SUBULUSSALAM'
 'SUMBA BARAT DAYA' 'TUBAN' 'TEGAL, KOTA' 'PASER' 'BULUNGAN' 'TULUNGAGUNG'
 'SUMBAWA BARAT' 'TEMANGGUNG' 'BARITO TIMUR' 'TANGERANG, KOTA' 'BERAU'
 'HALMAHERA UTARA' 'TANJUNG PINANG, KOTA' 'TRENGGALEK' 'TASIKMALAYA, KOTA'
 'TERNATE, KOTA' 'BOLAANG MONGONDOW TIMUR' 'SEMARANG' 'JAYAWIJAYA'
 'KULON PROGO' 'SUMBA BARAT' 'KEEROM' 'YOGYAKARTA, KOTA' 'DUMAI, KOTA'
 'BIAK NUMFOR' 'MIMIKA' 'MERAUKE' 'NGADA' 'NABIRE' 'SORONG'
 'TELUK BINTUNI' 'BOVEN DIGOEL' 'MALUKU TENGGARA'
 'KEPULAUAN SIAU TAGULANDAN' 'PESISIR BARAT' 'LINGGA' 'TOMOHON, KOTA'
 'HALMAHERA BARAT' 'KAIMANA' 'ACEH SINGKIL' 'LABUHAN BATU SELATAN'
 'ROTE NDAO' 'PRABUMULIH, KOTA' 'PONTIANAK' 'SABANG, KOTA'
 'KEPULAUAN MENTAWAI' 'SABU RAIJUA' 'SAMBAS' 'KEPULAUAN ARU'
 'MALUKU BARAT DAYA' 'MALUKU TENGGARA BARAT' 'SUPIORI' 'RAJA AMPAT'
 'SAWAHLUNTO, KOTA' 'TANAH DATAR' 'SINGKAWANG, KOTA' 'BONTANG, KOTA'
 'TEBING TINGGI, KOTA' 'CILEGON, KOTA' 'KEPULAUAN ANAMBAS' 'GUNUNG MAS'
 'SUKABUMI, KOTA' 'TARAKAN, KOTA' 'SURABAYA' 'KAB. TANGERANG' 'JAKARTA'
 'PASURUAN, KOTA' 'BANGKALAN' 'HULU SUNGAI TENGAH' 'ENDE' 'BANGKA TENGAH'
 'ALOR' 'KATINGAN' 'LUBUK LINGGAU, KOTA' 'LEMBATA' 'PAHUWATO' 'BANGLI'
 'MOJOKERTO, KOTA' 'SIKKA' 'SOLOK SELATAN' 'PEKALONGAN, KOTA' 'SUKAMARA'
 'TANA TIDUNG' 'SUBULUSSALAM, KOTA' 'JAKARTA PUSAT, KOTA' 'SUMBA TENGAH'
 'HALMAHERA TENGAH' 'TEGAL' 'KARANGANYAR' 'KERINCI' 'BELITUNG' 'WAKATOBI'
 'WONOSOBO' 'SELUMA' 'PANGKAJENE' 'MAMASA' 'PANGANDARAN' 'SOLOK, KOTA'
 'BELITUNG TIMUR' 'TELUK WONDAMA' 'BURU SELATAN'
 'KEPULAUAN SIAU TAGULANDANG BIARO']

In [21]:
# Menghapus ', KOTA' dan 'KAB.' dari kolom Alamat4
df_assessment['Alamat4'] = (
    df_assessment['Alamat4']
    .str.replace(', KOTA', '', regex=False)
    .str.replace('KAB.', '', regex=False)
    .str.strip()  # Menghapus spasi berlebih di awal/akhir string
)

# Menampilkan hasil
print(df_assessment['Alamat4'])

0           BENGKULU UTARA
1        LABUHANBATU UTARA
2        LABUHANBATU UTARA
3        LABUHANBATU UTARA
4        LABUHANBATU UTARA
               ...
4903    HUMBANG HASUNDUTAN
4904        TAPANULI UTARA
4905     KEPULAUAN MERANTI
4906        TAPANULI UTARA
4907                 DAIRI
Name: Alamat4, Length: 4908, dtype: object

In [22]:
df_assessment['Alamat4'] = df_assessment['Alamat4'].replace({
    'KEPULAUAN SIAU TAGULANDAN': 'KEPULAUAN SIAU TAGULANDANG BIARO'
})

In [23]:
df_assessment['Alamat4'] = df_assessment['Alamat4'].replace({
    'LABUHANBATU UTARA': 'LABUHAN BATU UTARA',
    'LABUHANBATU SELATAN': 'LABUHAN BATU SELATAN',
    'PANGKAJENE KEPULAUAN': 'PANGKAJENE',
    'LABUHANBATU': 'LABUHAN BATU'
})

In [24]:
df_assessment.loc[df_assessment['Alamat1'] == 'GD.GRAHAPRATAMALT.5,JL.MT HARYON', 'Alamat4'] = 'JAKARTA SELATAN'

In [25]:
# Menampilkan nilai unik pada kolom Alamat4 dan mengurutkan secara ascending
unique_alamat4 = sorted(df_assessment['Alamat4'].unique())

# Menampilkan hasil
print(unique_alamat4)

['ACEH BARAT', 'ACEH BARAT DAYA', 'ACEH BESAR', 'ACEH JAYA', 'ACEH SELATAN', 'ACEH SINGKIL', 'ACEH TAMIANG', 'ACEH TENGAH', 'ACEH TENGGARA', 'ACEH TIMUR', 'ACEH UTARA', 'AGAM', 'ALOR', 'AMBON', 'ASAHAN', 'BADUNG', 'BALANGAN', 'BALIKPAPAN', 'BANDA ACEH', 'BANDAR LAMPUNG', 'BANDUNG', 'BANDUNG BARAT', 'BANGGAI', 'BANGGAI KEPULAUAN', 'BANGKA', 'BANGKA BARAT', 'BANGKA SELATAN', 'BANGKA TENGAH', 'BANGKALAN', 'BANGLI', 'BANJAR', 'BANJARBARU', 'BANJARMASIN', 'BANJARNEGARA', 'BANTAENG', 'BANTUL', 'BANYUASIN', 'BANYUMAS', 'BANYUWANGI', 'BARITO KUALA', 'BARITO SELATAN', 'BARITO TIMUR', 'BARITO UTARA', 'BARRU', 'BATAM', 'BATANG', 'BATANGHARI', 'BATU', 'BATU BARA', 'BAU BAU', 'BEKASI', 'BELITUNG', 'BELITUNG TIMUR', 'BELU', 'BENER MERIAH', 'BENGKALIS', 'BENGKAYANG', 'BENGKULU', 'BENGKULU SELATAN', 'BENGKULU TENGAH', 'BENGKULU UTARA', 'BERAU', 'BIAK NUMFOR', 'BIMA', 'BINJAI', 'BINTAN', 'BIREUEN', 'BITUNG', 'BLITAR', 'BLORA', 'BOALEMO', 'BOGOR', 'BOJONEGORO', 'BOLAANG MONGONDOW', 'BOLAANG MONGONDOW SELATAN', 'BOLAANG MONGONDOW TIMUR', 'BOLAANG MONGONDOW UTARA', 'BOMBANA', 'BONDOWOSO', 'BONE', 'BONE BOLANGO', 'BONTANG', 'BOVEN DIGOEL', 'BOYOLALI', 'BREBES', 'BULELENG', 'BULUKUMBA', 'BULUNGAN', 'BUNGO', 'BUOL', 'BURU', 'BURU SELATAN', 'BUTON', 'BUTON UTARA', 'CIAMIS', 'CIANJUR', 'CILACAP', 'CILEGON', 'CIMAHI', 'CIREBON', 'DAIRI', 'DELI SERDANG', 'DEMAK', 'DENPASAR', 'DEPOK', 'DHARMASRAYA', 'DOMPU', 'DONGGALA', 'DUMAI', 'EMPAT LAWANG', 'ENDE', 'ENREKANG', 'FAK FAK', 'FLORES TIMUR', 'GARUT', 'GAYO LUES', 'GIANYAR', 'GORONTALO', 'GORONTALO UTARA', 'GOWA', 'GRESIK', 'GROBOGAN', 'GUNUNG KIDUL', 'GUNUNG MAS', 'GUNUNGSITOLI', 'HALMAHERA BARAT', 'HALMAHERA SELATAN', 'HALMAHERA TENGAH', 'HALMAHERA TIMUR', 'HALMAHERA UTARA', 'HULU SUNGAI SELATAN', 'HULU SUNGAI TENGAH', 'HULU SUNGAI UTARA', 'HUMBANG HASUNDUTAN', 'INDRAGIRI HILIR', 'INDRAGIRI HULU', 'INDRAMAYU', 'JAKARTA BARAT', 'JAKARTA PUSAT', 'JAKARTA SELATAN', 'JAKARTA TIMUR', 'JAKARTA UTARA', 'JAMBI', 'JAYAPURA', 'JAYAWIJAYA', 'JEMBER', 'JEMBRANA', 'JENEPONTO', 'JEPARA', 'JOMBANG', 'KAIMANA', 'KAMPAR', 'KAPUAS', 'KAPUAS HULU', 'KARANGANYAR', 'KARANGASEM', 'KARAWANG', 'KARIMUN', 'KARO', 'KATINGAN', 'KAUR', 'KEBUMEN', 'KEDIRI', 'KEEROM', 'KENDAL', 'KENDARI', 'KEPAHIANG', 'KEPULAUAN ANAMBAS', 'KEPULAUAN ARU', 'KEPULAUAN MENTAWAI', 'KEPULAUAN MERANTI', 'KEPULAUAN SANGIHE', 'KEPULAUAN SELAYAR', 'KEPULAUAN SIAU TAGULANDANG BIARO', 'KEPULAUAN SULA', 'KEPULAUAN TALAUD', 'KEPULAUAN YAPEN', 'KERINCI', 'KETAPANG', 'KLATEN', 'KLUNGKUNG', 'KOLAKA', 'KOLAKA UTARA', 'KONAWE', 'KONAWE SELATAN', 'KONAWE UTARA', 'KOTABARU', 'KOTAMOBAGU', 'KOTAWARINGIN BARAT', 'KOTAWARINGIN TIMUR', 'KUANTAN SINGINGI', 'KUBU RAYA', 'KUDUS', 'KULON PROGO', 'KUNINGAN', 'KUPANG', 'KUTAI BARAT', 'KUTAI KERTANEGARA', 'KUTAI TIMUR', 'LABUHAN BATU', 'LABUHAN BATU SELATAN', 'LABUHAN BATU UTARA', 'LAHAT', 'LAMANDAU', 'LAMONGAN', 'LAMPUNG BARAT', 'LAMPUNG SELATAN', 'LAMPUNG TENGAH', 'LAMPUNG TIMUR', 'LAMPUNG UTARA', 'LANDAK', 'LANGKAT', 'LANGSA', 'LEBAK', 'LEMBATA', 'LHOKSEUMAWE', 'LIMA PULUH KOTA', 'LINGGA', 'LOMBOK BARAT', 'LOMBOK TENGAH', 'LOMBOK TIMUR', 'LUBUK LINGGAU', 'LUMAJANG', 'LUWU', 'LUWU TIMUR', 'LUWU UTARA', 'MADIUN', 'MAGELANG', 'MAGETAN', 'MAJALENGKA', 'MAJENE', 'MAKASSAR', 'MALANG', 'MALINAU', 'MALUKU BARAT DAYA', 'MALUKU TENGAH', 'MALUKU TENGGARA', 'MALUKU TENGGARA BARAT', 'MAMASA', 'MAMUJU', 'MAMUJU UTARA', 'MANADO', 'MANDAILING NATAL', 'MANGGARAI', 'MANGGARAI BARAT', 'MANGGARAI TIMUR', 'MANOKWARI', 'MAPPI', 'MAROS', 'MATARAM', 'MEDAN', 'MELAWI', 'MERANGIN', 'MERAUKE', 'MESUJI', 'MIMIKA', 'MINAHASA', 'MINAHASA SELATAN', 'MINAHASA TENGGARA', 'MINAHASA UTARA', 'MOJOKERTO', 'MOROWALI', 'MUARA ENIM', 'MUARO JAMBI', 'MUKO MUKO', 'MUNA', 'MURUNG RAYA', 'MUSI BANYUASIN', 'MUSI RAWAS', 'NABIRE', 'NAGAN RAYA', 'NATUNA', 'NGADA', 'NGANJUK', 'NGAWI', 'NIAS', 'NIAS BARAT', 'NIAS SELATAN', 'NIAS UTARA', 'NUNUKAN', 'OGAN ILIR', 'OGAN KOMERING ILIR', 'OGAN KOMERING ULU', 'OKU SELATAN', 'OKU TIMUR', 'PACITAN', 'PADANG', 'PADANG LAWAS', 'PADANG LAWAS UTARA', 'PADANG PANJANG', 'PADANG PARIAMAN', 'PADANG SIDEMPUAN', 'PAGAR ALAM', 'PAHUWATO', 'PALANGKARAYA', 'PALEMBANG', 'PALOPO', 'PALU', 'PAMEKASAN', 'PANDEGLANG', 'PANGANDARAN', 'PANGKAJENE', 'PANGKAL PINANG', 'PARE PARE', 'PARIAMAN', 'PARIGI MOUTONG', 'PASAMAN', 'PASAMAN BARAT', 'PASER', 'PASURUAN', 'PATI', 'PAYAKUMBUH', 'PEKALONGAN', 'PEKANBARU', 'PELALAWAN', 'PEMALANG', 'PEMATANGSIANTAR', 'PENAJAM PASER UTARA', 'PESAWARAN', 'PESISIR BARAT', 'PESISIR SELATAN', 'PIDIE', 'PIDIE JAYA', 'PINRANG', 'POLEWALI MANDAR', 'PONOROGO', 'PONTIANAK', 'POSO', 'PRABUMULIH', 'PRINGSEWU', 'PROBOLINGGO', 'PULANG PISAU', 'PULAU MOROTAI', 'PURBALINGGA', 'PURWAKARTA', 'PURWOREJO', 'RAJA AMPAT', 'REJANG LEBONG', 'REMBANG', 'ROKAN HILIR', 'ROKAN HULU', 'ROTE NDAO', 'SABANG', 'SABU RAIJUA', 'SALATIGA', 'SAMARINDA', 'SAMBAS', 'SAMOSIR', 'SAMPANG', 'SANGGAU', 'SAROLANGUN', 'SAWAHLUNTO', 'SEKADAU', 'SELUMA', 'SEMARANG', 'SERAM BAGIAN BARAT', 'SERAM BAGIAN TIMUR', 'SERANG', 'SERDANG BEDAGAI', 'SERUYAN', 'SIAK', 'SIDENRENG RAPPANG', 'SIDOARJO', 'SIGI', 'SIJUNJUNG', 'SIKKA', 'SIMALUNGUN', 'SIMEULUE', 'SINGKAWANG', 'SINJAI', 'SINTANG', 'SITUBONDO', 'SLEMAN', 'SOLOK', 'SOLOK SELATAN', 'SOPPENG', 'SORONG', 'SRAGEN', 'SUBANG', 'SUBULUSSALAM', 'SUKABUMI', 'SUKAMARA', 'SUKOHARJO', 'SUMBA BARAT', 'SUMBA BARAT DAYA', 'SUMBA TENGAH', 'SUMBA TIMUR', 'SUMBAWA', 'SUMBAWA BARAT', 'SUMEDANG', 'SUMENEP', 'SUPIORI', 'SURABAYA', 'SURAKARTA', 'TABALONG', 'TABANAN', 'TAKALAR', 'TANA TIDUNG', 'TANA TORAJA', 'TANAH BUMBU', 'TANAH DATAR', 'TANAH LAUT', 'TANGERANG', 'TANGERANG SELATAN', 'TANGGAMUS', 'TANJUNG JABUNG BARAT', 'TANJUNG JABUNG TIMUR', 'TANJUNG PINANG', 'TAPANULI SELATAN', 'TAPANULI TENGAH', 'TAPANULI UTARA', 'TAPIN', 'TARAKAN', 'TASIKMALAYA', 'TEBING TINGGI', 'TEBO', 'TEGAL', 'TELUK BINTUNI', 'TELUK WONDAMA', 'TEMANGGUNG', 'TERNATE', 'TIDORE KEPULAUAN', 'TIMOR TENGAH SELATAN', 'TIMOR TENGAH UTARA', 'TOBA SAMOSIR', 'TOJO UNA UNA', 'TOLI TOLI', 'TOMOHON', 'TORAJA UTARA', 'TRENGGALEK', 'TUAL', 'TUBAN', 'TULANG BAWANG', 'TULANG BAWANG BARAT', 'TULUNGAGUNG', 'WAJO', 'WAKATOBI', 'WAY KANAN', 'WONOGIRI', 'WONOSOBO', 'YOGYAKARTA']

In [26]:
# Menampilkan seluruh nilai unik dari kolom Funcloc dalam bentuk list
unique_funcloc = df_assessment['Funcloc'].unique().tolist()

# Menampilkan hasil
print(unique_funcloc)

[100000000002, 100000000003, 100000000004, 100000000005, 100000000006, 100000000007, 100000000008, 100000000009, 100000000010, 100000000011, 100000000012, 100000000013, 100000000014, 100000000015, 100000000018, 100000000019, 100000000020, 100000000021, 100000000022, 100000000023, 100000000024, 100000000029, 100000000030, 100000000031, 100000000032, 100000000033, 100000000035, 100000000036, 100000000037, 100000000041, 100000000042, 100000000043, 100000000044, 100000000045, 100000000049, 100000000050, 100000000051, 100000000052, 100000000053, 100000000054, 100000000055, 100000000057, 100000000058, 100000000059, 100000000061, 100000000062, 100000000073, 100000000074, 100000000075, 100000000076, 100000000077, 100000000080, 100000000081, 100000000083, 100000000084, 100000000087, 100000000088, 100000000092, 100000000095, 100000000098, 100000000100, 100000000101, 100000000102, 100000000103, 100000000105, 100000000106, 100000000108, 100000000109, 100000000111, 100000000113, 100000000114, 100000000115, 100000000116, 100000000118, 100000000120, 100000000121, 100000000123, 100000000124, 100000000125, 100000000126, 100000000128, 100000000129, 100000000135, 100000000139, 100000000152, 100000000154, 100000000156, 100000000159, 100000000160, 100000000161, 100000000163, 100000000164, 100000000166, 100000000168, 100000000170, 100000000179, 100000000180, 100000000182, 100000000196, 100000000197, 100000000200, 100000000201, 100000000204, 100000000205, 100000000206, 100000000207, 100000000208, 100000000209, 100000000213, 100000000218, 100000000224, 100000000225, 100000000226, 100000000227, 100000000228, 100000000229, 100000000230, 100000000232, 100000000233, 100000000235, 100000000237, 100000000238, 100000000239, 100000000240, 100000000241, 100000000242, 100000000243, 100000000244, 100000000245, 100000000248, 100000000250, 100000000253, 100000000254, 100000000255, 100000000257, 100000000258, 100000000260, 100000000261, 100000000262, 100000000263, 100000000264, 100000000265, 100000000266, 100000000270, 100000000272, 100000000274, 100000000275, 100000000276, 100000000277, 100000000285, 100000000286, 100000000288, 100000000289, 100000000291, 100000000293, 100000000294, 100000000295, 100000000296, 100000000297, 100000000298, 100000000299, 100000000305, 100000000306, 100000000307, 100000000308, 100000000309, 100000000310, 100000000311, 100000000312, 100000000313, 100000000314, 100000000316, 100000000317, 100000000318, 100000000319, 100000000320, 100000000321, 100000000322, 100000000323, 100000000325, 100000000326, 100000000328, 100000000329, 100000000331, 100000000334, 100000000336, 100000000337, 100000000338, 100000000339, 100000000340, 100000000341, 100000000342, 100000000343, 100000000346, 100000000348, 100000000350, 100000000351, 100000000355, 100000000357, 100000000358, 100000000359, 100000000360, 100000000361, 100000000362, 100000000363, 100000000364, 100000000365, 100000000366, 100000000369, 100000000371, 100000000373, 100000000374, 100000000375, 100000000376, 100000000378, 100000000379, 100000000380, 100000000385, 100000000386, 100000000387, 100000000388, 100000000389, 100000000390, 100000000392, 100000000394, 100000000395, 100000000396, 100000000398, 100000000399, 100000000400, 100000000401, 100000000402, 100000000404, 100000000405, 100000000407, 100000000408, 100000000410, 100000000412, 100000000414, 100000000415, 100000000416, 100000000417, 100000000418, 100000000419, 100000000420, 100000000421, 100000000424, 100000000425, 100000000426, 100000000427, 100000000428, 100000000429, 100000000434, 100000000437, 100000000438, 100000000439, 100000000440, 100000000441, 100000000442, 100000000443, 100000000444, 100000000445, 100000000446, 100000000447, 100000000448, 100000000449, 100000000450, 100000000451, 100000000452, 100000000453, 100000000454, 100000000455, 100000000456, 100000000457, 100000000458, 100000000459, 100000000460, 100000000461, 100000000462, 100000000463, 100000000464, 100000000465, 100000000467, 100000000468, 100000000469, 100000000471, 100000000472, 100000000473, 100000000475, 100000000476, 100000000477, 100000000479, 100000000480, 100000000489, 100000000490, 100000000499, 100000000503, 100000000504, 100000000507, 100000000508, 100000000510, 100000000511, 100000000512, 100000000514, 100000000515, 100000000517, 100000000518, 100000000519, 100000000520, 100000000527, 100000000528, 100000000530, 100000000531, 100000000532, 100000000533, 100000000534, 100000000535, 100000000537, 100000000539, 100000000540, 100000000541, 100000000542, 100000000543, 100000000544, 100000000545, 100000000546, 100000000547, 100000000548, 100000000549, 100000000551, 100000000553, 100000000554, 100000000555, 100000000557, 100000000559, 100000000560, 100000000563, 100000000564, 100000000565, 100000000567, 100000000568, 100000000569, 100000000570, 100000000578, 100000000580, 100000000584, 100000000585, 100000000586, 100000000588, 100000000589, 100000000591, 100000000592, 100000000594, 100000000595, 100000000600, 100000000602, 100000000603, 100000000604, 100000000605, 100000000606, 100000000607, 100000000608, 100000000609, 100000000610, 100000000611, 100000000612, 100000000613, 100000000614, 100000000615, 100000000616, 100000000617, 100000000620, 100000000621, 100000000623, 100000000624, 100000000625, 100000000626, 100000000627, 100000000628, 100000000629, 100000000630, 100000000631, 100000000633, 100000000635, 100000000639, 100000000640, 100000000641, 100000000642, 100000000646, 100000000647, 100000000648, 100000000649, 100000000650, 100000000651, 100000000652, 100000000653, 100000000654, 100000000655, 100000000658, 100000000663, 100000000664, 100000000667, 100000000669, 100000000670, 100000000674, 100000000675, 100000000676, 100000000680, 100000000681, 100000000682, 100000000683, 100000000684, 100000000685, 100000000686, 100000000687, 100000000688, 100000000689, 100000000690, 100000000691, 100000000692, 100000000693, 100000000695, 100000000697, 100000000698, 100000000699, 100000000708, 100000000710, 100000000715, 100000000716, 100000000717, 100000000718, 100000000719, 100000000721, 100000000722, 100000000723, 100000000724, 100000000725, 100000000727, 100000000729, 100000000734, 100000000735, 100000000736, 100000000737, 100000000752, 100000000753, 100000000755, 100000000756, 100000000757, 100000000758, 100000000759, 100000000760, 100000000761, 100000000762, 100000000764, 100000000766, 100000000772, 100000000774, 100000000778, 100000000780, 100000000782, 100000000784, 100000000785, 100000000786, 100000000788, 100000000789, 100000000791, 100000000792, 100000000793, 100000000794, 100000000795, 100000000796, 100000000798, 100000000799, 100000000800, 100000000801, 100000000802, 100000000803, 100000000804, 100000000805, 100000000808, 100000000809, 100000000810, 100000000812, 100000000814, 100000000817, 100000000818, 100000000819, 100000000827, 100000000829, 100000000833, 100000000834, 100000000835, 100000000836, 100000000837, 100000000838, 100000000839, 100000000840, 100000000841, 100000000849, 100000000850, 100000000854, 100000000855, 100000000857, 100000000858, 100000000859, 100000000860, 100000000861, 100000000862, 100000000863, 100000000864, 100000000866, 100000000867, 100000000868, 100000000869, 100000000876, 100000000877, 100000000878, 100000000881, 100000000882, 100000000883, 100000000894, 100000000896, 100000000897, 100000000898, 100000000899, 100000000901, 100000000902, 100000000903, 100000000905, 100000000908, 100000000909, 100000000910, 100000000912, 100000000913, 100000000914, 100000000915, 100000000916, 100000000917, 100000000918, 100000000919, 100000000920, 100000000921, 100000000922, 100000000923, 100000000924, 100000000926, 100000000927, 100000000928, 100000000929, 100000000930, 100000000931, 100000000932, 100000000933, 100000000935, 100000000936, 100000000937, 100000000938, 100000000939, 100000000940, 100000000941, 100000000942, 100000000943, 100000000944, 100000000945, 100000000949, 100000000950, 100000000951, 100000000952, 100000000953, 100000000954, 100000000955, 100000000956, 100000000957, 100000000958, 100000000960, 100000000961, 100000000962, 100000000963, 100000000967, 100000000968, 100000000969, 100000000972, 100000000973, 100000000974, 100000000975, 100000000977, 100000000979, 100000000981, 100000000982, 100000000983, 100000000984, 100000000985, 100000000999, 100000001000, 100000001001, 100000001002, 100000001003, 100000001004, 100000001005, 100000001006, 100000001007, 100000001008, 100000001009, 100000001010, 100000001011, 100000001016, 100000001017, 100000001018, 100000001019, 100000001020, 100000001021, 100000001024, 100000001029, 100000001034, 100000001035, 100000001036, 100000001038, 100000001039, 100000001043, 100000001044, 100000001045, 100000001046, 100000001048, 100000001049, 100000001050, 100000001051, 100000001052, 100000001053, 100000001054, 100000001057, 100000001058, 100000001059, 100000001060, 100000001062, 100000001063, 100000001064, 100000001066, 100000001067, 100000001068, 100000001071, 100000001072, 100000001073, 100000001074, 100000001075, 100000001077, 100000001078, 100000001079, 100000001080, 100000001081, 100000001082, 100000001084, 100000001085, 100000001086, 100000001087, 100000001088, 100000001089, 100000001090, 100000001091, 100000001092, 100000001093, 100000001094, 100000001095, 100000001096, 100000001098, 100000001099, 100000001100, 100000001101, 100000001102, 100000001103, 100000001104, 100000001105, 100000001107, 100000001108, 100000001110, 100000001112, 100000001113, 100000001115, 100000001116, 100000001117, 100000001118, 100000001119, 100000001120, 100000001121, 100000001122, 100000001123, 100000001124, 100000001126, 100000001136, 100000001137, 100000001138, 100000001141, 100000001143, 100000001144, 100000001147, 100000001149, 100000001152, 100000001153, 100000001155, 100000001156, 100000001158, 100000001159, 100000001162, 100000001164, 100000001166, 100000001169, 100000001171, 100000001172, 100000001173, 100000001174, 100000001175, 100000001176, 100000001177, 100000001178, 100000001179, 100000001180, 100000001181, 100000001182, 100000001183, 100000001184, 100000001185, 100000001186, 100000001188, 100000001196, 100000001197, 100000001200, 100000001201, 100000001202, 100000001203, 100000001204, 100000001206, 100000001207, 100000001208, 100000001209, 100000001210, 100000001213, 100000001215, 100000001217, 100000001219, 100000001220, 100000001221, 100000001222, 100000001224, 100000001225, 100000001226, 100000001229, 100000001231, 100000001233, 100000001235, 100000001236, 100000001237, 100000001238, 100000001239, 100000001241, 100000001242, 100000001244, 100000001246, 100000001247, 100000001249, 100000001252, 100000001254, 100000001256, 100000001258, 100000001259, 100000001260, 100000001261, 100000001262, 100000001263, 100000001264, 100000001265, 100000001266, 100000001267, 100000001268, 100000001269, 100000001270, 100000001272, 100000001274, 100000001275, 100000001276, 100000001277, 100000001278, 100000001279, 100000001280, 100000001281, 100000001282, 100000001284, 100000001286, 100000001287, 100000001288, 100000001291, 100000001293, 100000001308, 100000001310, 100000001313, 100000001316, 100000001319, 100000001321, 100000001323, 100000001325, 100000001326, 100000001328, 100000001330, 100000001332, 100000001333, 100000001334, 100000001335, 100000001336, 100000001337, 100000001339, 100000001341, 100000001345, 100000001346, 100000001348, 100000001350, 100000001352, 100000001357, 100000001359, 100000001361, 100000001366, 100000001372, 100000001373, 100000001375, 100000001377, 100000001380, 100000001382, 100000001384, 100000001385, 100000001386, 100000001387, 100000001399, 100000001400, 100000001402, 100000001403, 100000001404, 100000001406, 100000001413, 100000001414, 100000001415, 100000001416, 100000001417, 100000001418, 100000001421, 100000001422, 100000001423, 100000001426, 100000001428, 100000001430, 100000001438, 100000001440, 100000001444, 100000001452, 100000001456, 100000001463, 100000001464, 100000001465, 100000001466, 100000001468, 100000001471, 100000001473, 100000001474, 100000001475, 100000001476, 100000001477, 100000001480, 100000001487, 100000001488, 100000001489, 100000001490, 100000001491, 100000001493, 100000001495, 100000001496, 100000001497, 100000001503, 100000001504, 100000001509, 100000001531, 100000001541, 100000001548, 100000001549, 100000001550, 100000001551, 100000001555, 100000001569, 100000001570, 100000001571, 100000001576, 100000001579, 100000001581, 100000001582, 100000001583, 100000001585, 100000001586, 100000001589, 100000001595, 100000001597, 100000001598, 100000001603, 100000001604, 100000001607, 100000001609, 100000001611, 100000001613, 100000001615, 100000001617, 100000001620, 100000001622, 100000001648, 100000001649, 100000001650, 100000001656, 100000001657, 100000001658, 100000001659, 100000001661, 100000001662, 100000001667, 100000001669, 100000001670, 100000001671, 100000001672, 100000001673, 100000001674, 100000001675, 100000001676, 100000001677, 100000001678, 100000001679, 100000001681, 100000001682, 100000001684, 100000001686, 100000001687, 100000001688, 100000001689, 100000001691, 100000001692, 100000001707, 100000001709, 100000001720, 100000001721, 100000001722, 100000001723, 100000001724, 100000001726, 100000001727, 100000001736, 100000001737, 100000001738, 100000001739, 100000001740, 100000001741, 100000001742, 100000001743, 100000001744, 100000001745, 100000001747, 100000001749, 100000001750, 100000001751, 100000001755, 100000001756, 100000001757, 100000001758, 100000001759, 100000001760, 100000001761, 100000001762, 100000001763, 100000001764, 100000001765, 100000001766, 100000001767, 100000001768, 100000001769, 100000001770, 100000001771, 100000001772, 100000001773, 100000001774, 100000001775, 100000001776, 100000001777, 100000001778, 100000001779, 100000001780, 100000001782, 100000001784, 100000001786, 100000001792, 100000001794, 100000001798, 100000001799, 100000001800, 100000001801, 100000001802, 100000001803, 100000001804, 100000001805, 100000001806, 100000001807, 100000001808, 100000001809, 100000001810, 100000001811, 100000001812, 100000001813, 100000001814, 100000001815, 100000001816, 100000001817, 100000001818, 100000001819, 100000001820, 100000001821, 100000001822, 100000001823, 100000001824, 100000001825, 100000001826, 100000001828, 100000001831, 100000001832, 100000001833, 100000001835, 100000001836, 100000001838, 100000001839, 100000001851, 100000001879, 100000001886, 100000001887, 100000001888, 100000001889, 100000001890, 100000001891, 100000001892, 100000001893, 100000001897, 100000001899, 100000001901, 100000001903, 100000001904, 100000001907, 100000001909, 100000001910, 100000001915, 100000001916, 100000001917, 100000001918, 100000001919, 100000001920, 100000001921, 100000001927, 100000001928, 100000001930, 100000001934, 100000001935, 100000001936, 100000001946, 100000001948, 100000001950, 100000001951, 100000001952, 100000001953, 100000001954, 100000001955, 100000001956, 100000001957, 100000001958, 100000001963, 100000001964, 100000001965, 100000001968, 100000001969, 100000001971, 100000001972, 100000001973, 100000001978, 100000001980, 100000001981, 100000001982, 100000001983, 100000001984, 100000001985, 100000001986, 100000001987, 100000001988, 100000001989, 100000001990, 100000001991, 100000001992, 100000001993, 100000001994, 100000001995, 100000001996, 100000001997, 100000001998, 100000001999, 100000002000, 100000002001, 100000002002, 100000002003, 100000002004, 100000002005, 100000002006, 100000002008, 100000002009, 100000002011, 100000002015, 100000002017, 100000002022, 100000002023, 100000002024, 100000002025, 100000002026, 100000002028, 100000002030, 100000002031, 100000002033, 100000002034, 100000002035, 100000002036, 100000002037, 100000002039, 100000002041, 100000002042, 100000002043, 100000002044, 100000002045, 100000002047, 100000002048, 100000002049, 100000002050, 100000002052, 100000002053, 100000002054, 100000002055, 100000002056, 100000002057, 100000002060, 100000002061, 100000002062, 100000002063, 100000002065, 100000002070, 100000002071, 100000002072, 100000002074, 100000002088, 100000002091, 100000002092, 100000002093, 100000002094, 100000002095, 100000002096, 100000002097, 100000002098, 100000002099, 100000002100, 100000002101, 100000002102, 100000002103, 100000002104, 100000002105, 100000002106, 100000002108, 100000002109, 100000002110, 100000002112, 100000002113, 100000002114, 100000002115, 100000002116, 100000002117, 100000002118, 100000002119, 100000002120, 100000002121, 100000002122, 100000002123, 100000002124, 100000002125, 100000002126, 100000002128, 100000002129, 100000002130, 100000002132, 100000002133, 100000002134, 100000002135, 100000002140, 100000002142, 100000002144, 100000002145, 100000002146, 100000002147, 100000002149, 100000002152, 100000002153, 100000002154, 100000002155, 100000002157, 100000002159, 100000002162, 100000002163, 100000002164, 100000002165, 100000002166, 100000002167, 100000002168, 100000002171, 100000002172, 100000002173, 100000002175, 100000002176, 100000002177, 100000002179, 100000002180, 100000002186, 100000002189, 100000002192, 100000002195, 100000002200, 100000002201, 100000002202, 100000002203, 100000002204, 100000002205, 100000002207, 100000002209, 100000002212, 100000002214, 100000002220, 100000002221, 100000002222, 100000002223, 100000002227, 100000002228, 100000002229, 100000002230, 100000002231, 100000002232, 100000002235, 100000002236, 100000002237, 100000002238, 100000002239, 100000002240, 100000002241, 100000002242, 100000002243, 100000002245, 100000002246, 100000002247, 100000002251, 100000002253, 100000002254, 100000002255, 100000002256, 100000002257, 100000002258, 100000002259, 100000002260, 100000002261, 100000002262, 100000002265, 100000002269, 100000002270, 100000002272, 100000002276, 100000002277, 100000002278, 100000002279, 100000002280, 100000002283, 100000002285, 100000002286, 100000002288, 100000002289, 100000002290, 100000002291, 100000002293, 100000002294, 100000002295, 100000002296, 100000002297, 100000002298, 100000002300, 100000002301, 100000002302, 100000002303, 100000002304, 100000002305, 100000002306, 100000002307, 100000002308, 100000002309, 100000002310, 100000002312, 100000002313, 100000002314, 100000002315, 100000002316, 100000002317, 100000002319, 100000002321, 100000002322, 100000002323, 100000002325, 100000002326, 100000002327, 100000002328, 100000002329, 100000002330, 100000002331, 100000002332, 100000002333, 100000002336, 100000002337, 100000002339, 100000002340, 100000002341, 100000002344, 100000002367, 100000002368, 100000002369, 100000002370, 100000002371, 100000002374, 100000002379, 100000002380, 100000002381, 100000002389, 100000002390, 100000002391, 100000002392, 100000002393, 100000002394, 100000002402, 100000002403, 100000002404, 100000002410, 100000002411, 100000002412, 100000002418, 100000002419, 100000002421, 100000002424, 100000002425, 100000002427, 100000002428, 100000002430, 100000002433, 100000002437, 100000002439, 100000002441, 100000002442, 100000002451, 100000002454, 100000002455, 100000002456, 100000002457, 100000002458, 100000002459, 100000002461, 100000002462, 100000002463, 100000002464, 100000002465, 100000002466, 100000002467, 100000002468, 100000002469, 100000002470, 100000002471, 100000002472, 100000002473, 100000002474, 100000002475, 100000002477, 100000002480, 100000002481, 100000002482, 100000002489, 100000002491, 100000002492, 100000002493, 100000002494, 100000002495, 100000002496, 100000002497, 100000002499, 100000002501, 100000002502, 100000002504, 100000002505, 100000002506, 100000002507, 100000002508, 100000002509, 100000002510, 100000002511, 100000002512, 100000002514, 100000002517, 100000002518, 100000002520, 100000002525, 100000002526, 100000002528, 100000002530, 100000002531, 100000002532, 100000002533, 100000002534, 100000002535, 100000002536, 100000002537, 100000002539, 100000002541, 100000002542, 100000002543, 100000002544, 100000002545, 100000002546, 100000002547, 100000002548, 100000002549, 1000000

In [27]:
# Menghitung jumlah nilai unik pada kolom Funcloc
num_unique_funcloc = len(df_assessment['Funcloc'].unique())

# Menampilkan hasil
print(num_unique_funcloc)

4908

In [28]:
# Menghitung panjang dari setiap nilai unik pada kolom Funcloc
funcloc_lengths = df_assessment['Funcloc'].astype(str).apply(len).unique()

# Menampilkan hasil
print(funcloc_lengths)

[12]

In [29]:
# Mengonversi kolom Funcloc ke format string
df_assessment['Funcloc'] = df_assessment['Funcloc'].astype(str)

In [30]:
df_assessment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4908 entries, 0 to 4907
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Funcloc   4908 non-null   object
 1   Alamat1   4908 non-null   object
 2   Alamat2   4884 non-null   object
 3   Alamat3   4877 non-null   object
 4   Alamat4   4908 non-null   object
 5   SiteName  4908 non-null   object
dtypes: object(6)
memory usage: 230.2+ KB

In [31]:
# Menggunakan rank dengan method='dense' dan mengonversi hasil ke integer
df_assessment['Funcloc_Order'] = df_assessment['Funcloc'].rank(method='dense', ascending=True).astype(int)

In [32]:
df_assessment.head()

,Funcloc,Alamat1,Alamat2,Alamat3,Alamat4,SiteName,Funcloc_Order
0,100000000002,DESA ALUN DUA,DESA ALUN DUA,KECAMATAN KERKAP,BENGKULU UTARA,STEELE-PHILLIPS,1
1,100000000003,DESA PADANG MANINJAU,KEL. DESA PADANG MANINJAU,KEC. AEK KUO,LABUHAN BATU UTARA,"HERRERA, BARNES AND TAYLOR",2
2,100000000004,DESA BIO-BIO,KEL. BANDAR DURIAN,KEC. AEK NATAS,LABUHAN BATU UTARA,LEE GROUP,3
3,100000000005,RINTIS KACANG,DESA PANGAKALAN,KEC. AEK NATAS,LABUHAN BATU UTARA,BARTON INC,4
4,100000000006,DUSUN VI SIDODADI,DESA MARBAU SELATAN,KEC. MARBAU,LABUHAN BATU UTARA,"COLE, MOLINA AND WILLIAMS",5

In [33]:
# Menggabungkan df_assessment dan df_city_indonesia menggunakan outer join
merged_df_assessment = pd.merge(df_assessment, df_city_indonesia, left_on='Alamat4', right_on='City', how='outer')

In [34]:
merged_df_assessment.head()

,Funcloc,Alamat1,Alamat2,Alamat3,Alamat4,SiteName,Funcloc_Order,City,CityCode,Province,Region,RegionalCode
0,100000002328,JL. MEULABOH TUTUT KM 7,DESA BLANG BERANDANG,KEC. JOHAN PAHLAWAN,ACEH BARAT,RUIZ-LONG,1312.0,ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1
1,100000002329,"BEUTAWI PAYA DUA,","KEL. DESA PAYA DUA, X",KEC. WOYLA,ACEH BARAT,BRADFORD AND SONS,1313.0,ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1
2,100000002330,DSN I KEL.DESA PULO PEUNGOH KEC.MEUREBO,DS PULO TEUNGOH,MEUREBO,ACEH BARAT,MATTHEWS INC,1314.0,ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1
3,100000012864,JL. MEULABOH,KEL. ALUE BILIE,KEC. ALUE BILIE,ACEH BARAT,"WILSON, BERRY AND GRIFFIN",3332.0,ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1
4,100000014390,"JL. MEULABOH Â€“ TUTUN KM 10,","KEL. GAMPONG ALUE TAMPAK,",KEC. KAWAY,ACEH BARAT,SMITH PLC,3655.0,ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1

In [35]:
merged_df_assessment.columns

Index(['Funcloc', 'Alamat1', 'Alamat2', 'Alamat3', 'Alamat4', 'SiteName',
       'Funcloc_Order', 'City', 'CityCode', 'Province', 'Region',
       'RegionalCode'],
      dtype='object')

In [36]:
merged_df_assessment.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5684 entries, 0 to 5683
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Funcloc        5637 non-null   object
 1   Alamat1        5637 non-null   object
 2   Alamat2        5605 non-null   object
 3   Alamat3        5595 non-null   object
 4   Alamat4        5637 non-null   object
 5   SiteName       5637 non-null   object
 6   Funcloc_Order  5637 non-null   float64
 7   City           5684 non-null   object
 8   CityCode       5684 non-null   object
 9   Province       5684 non-null   object
 10  Region         5684 non-null   object
 11  RegionalCode   5684 non-null   int64
dtypes: float64(1), int64(1), object(10)
memory usage: 533.0+ KB

In [37]:
merged_df_assessment

,Funcloc,Alamat1,Alamat2,Alamat3,Alamat4,SiteName,Funcloc_Order,City,CityCode,Province,Region,RegionalCode
0,100000002328,JL. MEULABOH TUTUT KM 7,DESA BLANG BERANDANG,KEC. JOHAN PAHLAWAN,ACEH BARAT,RUIZ-LONG,1312.0,ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1
1,100000002329,"BEUTAWI PAYA DUA,","KEL. DESA PAYA DUA, X",KEC. WOYLA,ACEH BARAT,BRADFORD AND SONS,1313.0,ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1
2,100000002330,DSN I KEL.DESA PULO PEUNGOH KEC.MEUREBO,DS PULO TEUNGOH,MEUREBO,ACEH BARAT,MATTHEWS INC,1314.0,ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1
3,100000012864,JL. MEULABOH,KEL. ALUE BILIE,KEC. ALUE BILIE,ACEH BARAT,"WILSON, BERRY AND GRIFFIN",3332.0,ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1
4,100000014390,"JL. MEULABOH Â€“ TUTUN KM 10,","KEL. GAMPONG ALUE TAMPAK,",KEC. KAWAY,ACEH BARAT,SMITH PLC,3655.0,ACEH BARAT,MBO,PROVINSI ACEH,SUMBAGUT,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5679,100000003926,JLN. GLAGAHSARI UMBULHARJO YOGYAKARTA,"KEL. YOGYAKARTA,","KEC. YOGYAKARTA,",YOGYAKARTA,WELCH-FLORES,2173.0,YOGYAKARTA,YYK,DI YOGYAKARTA,JAWA TENGAH,6
5680,100000004809,"WISMA MM UGM ,JL.COLOMBO DIY.",DIY,DIY,YOGYAKARTA,"FRENCH, BARNETT AND ADAMS",2187.0,YOGYAKARTA,YYK,DI YOGYAKARTA,JAWA TENGAH,6
5681,100000004865,DEPAN STADION MANDALA KRIDA (COMBAT),MANDALA KRIDA,UMBUL HARJO,YOGYAKARTA,ZIMMERMAN-STOKES,2200.0,YOGYAKARTA,YYK,DI YOGYAKARTA,JAWA TENGAH,6
5682,100000006467,JLN. TRIKORA,"PRAWIRODIRJAN,",GONDOMANAN,YOGYAKARTA,LEACH-CORTEZ,2916.0,YOGYAKARTA,YYK,DI YOGYAKARTA,JAWA TENGAH,6
5683,100000013640,JLN. LAKSDA ADISUCIPTO YOGYAKARTA,DIY,DIY,YOGYAKARTA,WALLACE LTD,3598.0,YOGYAKARTA,YYK,DI YOGYAKARTA,JAWA TENGAH,6

In [38]:
# Mengurutkan merged_df_assessment berdasarkan kolom Funcloc secara ascending
merged_df_assessment = merged_df_assessment.sort_values(by='Funcloc', ascending=True)

In [39]:
merged_df_assessment

,Funcloc,Alamat1,Alamat2,Alamat3,Alamat4,SiteName,Funcloc_Order,City,CityCode,Province,Region,RegionalCode
947,100000000002,DESA ALUN DUA,DESA ALUN DUA,KECAMATAN KERKAP,BENGKULU UTARA,STEELE-PHILLIPS,1.0,BENGKULU UTARA,AGM,PROVINSI BENGKULU,SUMBAGSEL,3
2755,100000000003,DESA PADANG MANINJAU,KEL. DESA PADANG MANINJAU,KEC. AEK KUO,LABUHAN BATU UTARA,"HERRERA, BARNES AND TAYLOR",2.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1
2756,100000000004,DESA BIO-BIO,KEL. BANDAR DURIAN,KEC. AEK NATAS,LABUHAN BATU UTARA,LEE GROUP,3.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1
2757,100000000005,RINTIS KACANG,DESA PANGAKALAN,KEC. AEK NATAS,LABUHAN BATU UTARA,BARTON INC,4.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1
2758,100000000006,DUSUN VI SIDODADI,DESA MARBAU SELATAN,KEC. MARBAU,LABUHAN BATU UTARA,"COLE, MOLINA AND WILLIAMS",5.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TANJUNG BALAI,TJB,PROVINSI SUMATERA UTARA,SUMBAGUT,1
5557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TOLIKARA,KBG,PROVINSI PAPUA,PUMA,11
5619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WAROPEN,BTW,PROVINSI PAPUA,PUMA,11
5677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YAHUKIMO,SMH,PROVINSI PAPUA,PUMA,11
5678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,YALIMO,ELL,PROVINSI PAPUA,PUMA,11

In [40]:
unique_citycode = merged_df_assessment['CityCode'].unique()

# Menampilkan hasil
print(unique_citycode)

['AGM' 'AKK' 'AMB' 'MSH' 'APN' 'ARM' 'BBU' 'BDL' 'BDW' 'BEK' 'BGK' 'BGL'
 'WHO' 'BIM' 'BIT' 'BJB' 'BKN' 'BKO' 'CKR' 'BKS' 'BLA' 'BLG' 'BLK' 'BLN'
 'BLS' 'KRB' 'BNA' 'STB' 'BNJ' 'BPD' 'BPP' 'BSB' 'BTG' 'BTM' 'BTU' 'BYW'
 'BGR' 'CBI' 'TNG' 'TGR' 'CJR' 'CKG' 'RKB' 'CLP' 'CMH' 'CMS' 'DGL' 'PAL'
 'DLS' 'DPK' 'DPU' 'DRH' 'DTH' 'ENR' 'GDT' 'GIN' 'GNS' 'GNT' 'GRG' 'GRT'
 'GSK' 'GST' 'IDL' 'IDM' 'JAP' 'JBG' 'JMB' 'JMR' 'JNP' 'KAG' 'KBJ' 'KBM'
 'KBR' 'KDI' 'PSW' 'BAU' 'RAH' 'UNH' 'KDL' 'KDR' 'KEP' 'KIS' 'KKA' 'SOR'
 'BDG' 'KNG' 'BLT' 'KNR' 'KPG' 'KPN' 'MLG' 'KRA' 'LGS' 'KRS' 'PBL' 'PNG'
 'KTG' 'KTN' 'KWG' 'CPT' 'KYB' 'LBP' 'LBS' 'LHM' 'LHT' 'LIW' 'LLK' 'LMG'
 'LMJ' 'LMP' 'LRT' 'LSK' 'LSM' 'LTU' 'LWK' 'TRT' 'MAB' 'MJY' 'MAD' 'MAK'
 'MAM' 'MBL' 'MBN' 'MDN' 'MGT' 'MJK' 'MJN' 'MKD' 'MGG' 'MKS' 'MLL' 'MPR'
 'MRB' 'MRD' 'MRE' 'MRS' 'MRT' 'MSJ' 'MTK' 'MTR' 'MTW' 'NGW' 'NJK' 'NLA'
 'NPH' 'NPM' 'PBR' 'PBU' 'PDG' 'PIN' 'PKB' 'PKJ' 'PKK' 'PLG' 'PLK' 'PLP'
 'PLW' 'PML' 'PMS' 'PRE' 'PRG' 'PRP' 'PSP' 'PSN' 'PSR' 'PTI' 'PTS' 'PWD'
 'PWK' 'PWR' 'PWT' 'PYB' 'RAP' 'RGT' 'RTN' 'SAG' 'SAK' 'SBG' 'SBH' 'SBM'
 'SKB' 'CBN' 'SBR' 'SBW' 'SBY' 'SDA' 'SDK' 'SDN' 'KTB' 'SDR' 'SGB' 'SGM'
 'SGN' 'SGR' 'SGT' 'SIT' 'SKG' 'SKH' 'SKT' 'SKY' 'SMG' 'UNR' 'SMR' 'SNB'
 'SNG' 'SNJ' 'SNN' 'SNT' 'SOE' 'SPA' 'TSM' 'SPE' 'SPT' 'SRG' 'SRH' 'SRK'
 'SRL' 'SRP' 'STG' 'SWW' 'TAB' 'TBG' 'TBH' 'TBK' 'TBL' 'TDR' 'THN' 'TJG'
 'TJP' 'TKA' 'TKN' 'TLD' 'TLI' 'TLK' 'TMT' 'TNN' 'TRG' 'TTG' 'TTN' 'TUL'
 'TWG' 'UJT' 'WGD' 'WGP' 'WNG' 'WNO' 'WNS' 'WTP' 'ADL' 'KRT' 'AMR' 'PRN'
 'AMT' 'ARS' 'SLK' 'ATB' 'BAN' 'BAR' 'BBS' 'BEN' 'BHN' 'MNA' 'BIR' 'BJR'
 'MTP' 'BJM' 'BJN' 'BLU' 'BNG' 'BNR' 'BNT' 'BRG' 'BRK' 'BTA' 'BTL' 'BUL'
 'BYL' 'CAG' 'CRP' 'DMK' 'DPR' 'FFK' 'GGP' 'MGL' 'GTO' 'LBT' 'JPA' 'JTH'
 'RMB' 'LSS' 'KDS' 'KFM' 'KGN' 'KJN' 'PKL' 'KLA' 'KLK' 'KLN' 'KLP' 'KLT'
 'KOT' 'KPH' 'KPI' 'KTP' 'KWD' 'LBA' 'LBB' 'LBJ' 'MBO' 'MGN' 'MGW' 'MJL'
 'MKM' 'MLN' 'MND' 'MNK' 'MRH' 'MRJ' 'MRN' 'MSB' 'MSK' 'DRB' 'NBA' 'NGA'
 'NGB' 'NGP' 'NNK' 'PMN' 'PAD' 'PBG' 'PCT' 'PDP' 'PGA' 'PGP' 'PKY' 'PLI'
 'PLJ' 'PMK' 'PNJ' 'PNN' 'PPS' 'PRC' 'PRR' 'PRW' 'PSO' 'PTK' 'PYA' 'PYH'
 'RAN' 'RBG' 'RTA' 'RTG' 'RTP' 'SDW' 'SED' 'SEL' 'SGI' 'BKJ' 'SGL' 'SKM'
 'SKN' 'SLT' 'SMD' 'SMN' 'SMP' 'SPG' 'SRY' 'SRU' 'STR' 'SUS' 'TAM' 'TBN'
 'SLW' 'TGL' 'TGT' 'TJS' 'TLG' 'TLW' 'TMG' 'TML' 'TNR' 'TOB' 'TPG' 'TRK'
 'TTE' 'TTY' 'WAM' 'WAT' 'WKB' 'WRS' 'YYK' 'DUM' 'BIK' 'TIM' 'MRK' 'BJW'
 'NAB' 'AMS' 'SON' 'BTI' 'TMR' 'ODS' 'KRU' 'DKL' 'TMH' 'JLL' 'KMN' 'SKL'
 'BAA' 'PBM' 'SAB' 'TPT' 'SBB' 'SBS' 'DOB' 'TKR' 'SML' 'SRW' 'WAS' 'SWL'
 'BSK' 'SKW' 'BON' 'TBT' 'CLG' 'TRP' 'KKN' 'TAR' 'BKL' 'BRB' 'END' 'KBA'
 'KLB' 'KSN' 'LLG' 'LWB' 'MAR' 'BLI' 'MME' 'PDA' 'SKR' 'TDP' 'TNA' 'WBL'
 'WED' 'KRG' 'SPN' 'TDN' 'WGW' 'WSB' 'TAS' 'MMS' 'PAG' 'MGR' 'RAS' 'NMR'
 'AGT' 'BGI' 'BKT' 'BAG' 'LBK' 'TIG' 'KGM' 'SGP' 'SKD' 'KSU' 'TRW' 'LGR'
 'TOM' 'TUB' 'TJN' 'UJB' 'BTN' 'BRM' 'KBK' 'TBD' 'RNK' 'AFT' 'MPW' 'MET'
 'KND' 'SWG' 'RPT' 'MBY' 'KYM' 'SAL' 'ERT' 'ANG' 'OSB' 'TLB' 'BOB' 'ILG'
 'MUL' 'SMI' 'TMB' 'FEF' 'TJB' 'KBG' 'BTW' 'SMH' 'ELL']

In [41]:
unique_regionalcode = merged_df_assessment['RegionalCode'].unique()

# Menampilkan hasil
print(unique_regionalcode)

[ 3  1 11 10  7  9  8  2  4  6  5]

In [42]:
merged_df_assessment = merged_df_assessment.dropna(subset=['Funcloc'])

In [43]:
merged_df_assessment

,Funcloc,Alamat1,Alamat2,Alamat3,Alamat4,SiteName,Funcloc_Order,City,CityCode,Province,Region,RegionalCode
947,100000000002,DESA ALUN DUA,DESA ALUN DUA,KECAMATAN KERKAP,BENGKULU UTARA,STEELE-PHILLIPS,1.0,BENGKULU UTARA,AGM,PROVINSI BENGKULU,SUMBAGSEL,3
2755,100000000003,DESA PADANG MANINJAU,KEL. DESA PADANG MANINJAU,KEC. AEK KUO,LABUHAN BATU UTARA,"HERRERA, BARNES AND TAYLOR",2.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1
2756,100000000004,DESA BIO-BIO,KEL. BANDAR DURIAN,KEC. AEK NATAS,LABUHAN BATU UTARA,LEE GROUP,3.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1
2757,100000000005,RINTIS KACANG,DESA PANGAKALAN,KEC. AEK NATAS,LABUHAN BATU UTARA,BARTON INC,4.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1
2758,100000000006,DUSUN VI SIDODADI,DESA MARBAU SELATAN,KEC. MARBAU,LABUHAN BATU UTARA,"COLE, MOLINA AND WILLIAMS",5.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1899,100000059183,DUSUN TIGA DESA AEK NAULI 2 KEC.POLLUNG,DS AEK NAULI 2,POLLUNG,HUMBANG HASUNDUTAN,HURLEY INC,4904.0,HUMBANG HASUNDUTAN,DLS,PROVINSI SUMATERA UTARA,SUMBAGUT,1
5358,100000059265,DESA PANSUR NATOLU KEC.PANGARIBUAN,DS PANSUR NATOLU,PANGARIBUAN,TAPANULI UTARA,WRIGHT-GARZA,4905.0,TAPANULI UTARA,TRT,PROVINSI SUMATERA UTARA,SUMBAGUT,1
2383,100000059267,JL.BANGLAS GG DAMAI RT.02/02,DS SELATPANJANG TIMUR,TEBING TINGGI,KEPULAUAN MERANTI,BENTON-PEREZ,4906.0,KEPULAUAN MERANTI,TTG,PROVINSI RIAU,SUMBAGTENG,2
5359,100000059268,DESA BANUAJI I KEC.ADIANKOTING,DS BANUAJI I,ADIANKOTING,TAPANULI UTARA,INGRAM-BROWN,4907.0,TAPANULI UTARA,TRT,PROVINSI SUMATERA UTARA,SUMBAGUT,1
1606,100000059270,DESA PERJUANGAN KEC.SUMBUL KAB.DAIRI,DS PERJUANGAN,SUMBUL,DAIRI,"BLACKWELL, RICHARDS AND SANDERS",4908.0,DAIRI,SDK,PROVINSI SUMATERA UTARA,SUMBAGUT,1

In [44]:
merged_df_assessment.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5637 entries, 947 to 1606
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Funcloc        5637 non-null   object
 1   Alamat1        5637 non-null   object
 2   Alamat2        5605 non-null   object
 3   Alamat3        5595 non-null   object
 4   Alamat4        5637 non-null   object
 5   SiteName       5637 non-null   object
 6   Funcloc_Order  5637 non-null   float64
 7   City           5637 non-null   object
 8   CityCode       5637 non-null   object
 9   Province       5637 non-null   object
 10  Region         5637 non-null   object
 11  RegionalCode   5637 non-null   int64
dtypes: float64(1), int64(1), object(10)
memory usage: 572.5+ KB

In [45]:
# Mengekspor DataFrame merged_df_assessment ke file Excel
merged_df_assessment.to_excel('merged_df_assessment.xlsx', index=False)

In [46]:
merged_df_assessment['Sequence'] = merged_df_assessment.groupby('CityCode')['Funcloc'].rank(method='first').astype(int).astype(str).str.zfill(3)

<ipython-input-46-5c4d63db57ee>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df_assessment['Sequence'] = merged_df_assessment.groupby('CityCode')['Funcloc'].rank(method='first').astype(int).astype(str).str.zfill(3)

In [47]:
merged_df_assessment

,Funcloc,Alamat1,Alamat2,Alamat3,Alamat4,SiteName,Funcloc_Order,City,CityCode,Province,Region,RegionalCode,Sequence
947,100000000002,DESA ALUN DUA,DESA ALUN DUA,KECAMATAN KERKAP,BENGKULU UTARA,STEELE-PHILLIPS,1.0,BENGKULU UTARA,AGM,PROVINSI BENGKULU,SUMBAGSEL,3,001
2755,100000000003,DESA PADANG MANINJAU,KEL. DESA PADANG MANINJAU,KEC. AEK KUO,LABUHAN BATU UTARA,"HERRERA, BARNES AND TAYLOR",2.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,001
2756,100000000004,DESA BIO-BIO,KEL. BANDAR DURIAN,KEC. AEK NATAS,LABUHAN BATU UTARA,LEE GROUP,3.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,002
2757,100000000005,RINTIS KACANG,DESA PANGAKALAN,KEC. AEK NATAS,LABUHAN BATU UTARA,BARTON INC,4.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,003
2758,100000000006,DUSUN VI SIDODADI,DESA MARBAU SELATAN,KEC. MARBAU,LABUHAN BATU UTARA,"COLE, MOLINA AND WILLIAMS",5.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,004
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,100000059183,DUSUN TIGA DESA AEK NAULI 2 KEC.POLLUNG,DS AEK NAULI 2,POLLUNG,HUMBANG HASUNDUTAN,HURLEY INC,4904.0,HUMBANG HASUNDUTAN,DLS,PROVINSI SUMATERA UTARA,SUMBAGUT,1,014
5358,100000059265,DESA PANSUR NATOLU KEC.PANGARIBUAN,DS PANSUR NATOLU,PANGARIBUAN,TAPANULI UTARA,WRIGHT-GARZA,4905.0,TAPANULI UTARA,TRT,PROVINSI SUMATERA UTARA,SUMBAGUT,1,015
2383,100000059267,JL.BANGLAS GG DAMAI RT.02/02,DS SELATPANJANG TIMUR,TEBING TINGGI,KEPULAUAN MERANTI,BENTON-PEREZ,4906.0,KEPULAUAN MERANTI,TTG,PROVINSI RIAU,SUMBAGTENG,2,010
5359,100000059268,DESA BANUAJI I KEC.ADIANKOTING,DS BANUAJI I,ADIANKOTING,TAPANULI UTARA,INGRAM-BROWN,4907.0,TAPANULI UTARA,TRT,PROVINSI SUMATERA UTARA,SUMBAGUT,1,016
1606,100000059270,DESA PERJUANGAN KEC.SUMBUL KAB.DAIRI,DS PERJUANGAN,SUMBUL,DAIRI,"BLACKWELL, RICHARDS AND SANDERS",4908.0,DAIRI,SDK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,017

In [48]:
merged_df_assessment['Internal Site ID'] = merged_df_assessment['CityCode'] + '-' + merged_df_assessment['RegionalCode'].astype(str).str.zfill(2) + '-' + merged_df_assessment['Sequence']

<ipython-input-48-8148b38db698>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df_assessment['Internal Site ID'] = merged_df_assessment['CityCode'] + '-' + merged_df_assessment['RegionalCode'].astype(str).str.zfill(2) + '-' + merged_df_assessment['Sequence']

In [49]:
merged_df_assessment

,Funcloc,Alamat1,Alamat2,Alamat3,Alamat4,SiteName,Funcloc_Order,City,CityCode,Province,Region,RegionalCode,Sequence,Internal Site ID
947,100000000002,DESA ALUN DUA,DESA ALUN DUA,KECAMATAN KERKAP,BENGKULU UTARA,STEELE-PHILLIPS,1.0,BENGKULU UTARA,AGM,PROVINSI BENGKULU,SUMBAGSEL,3,001,AGM-03-001
2755,100000000003,DESA PADANG MANINJAU,KEL. DESA PADANG MANINJAU,KEC. AEK KUO,LABUHAN BATU UTARA,"HERRERA, BARNES AND TAYLOR",2.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,001,AKK-01-001
2756,100000000004,DESA BIO-BIO,KEL. BANDAR DURIAN,KEC. AEK NATAS,LABUHAN BATU UTARA,LEE GROUP,3.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,002,AKK-01-002
2757,100000000005,RINTIS KACANG,DESA PANGAKALAN,KEC. AEK NATAS,LABUHAN BATU UTARA,BARTON INC,4.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,003,AKK-01-003
2758,100000000006,DUSUN VI SIDODADI,DESA MARBAU SELATAN,KEC. MARBAU,LABUHAN BATU UTARA,"COLE, MOLINA AND WILLIAMS",5.0,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,004,AKK-01-004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,100000059183,DUSUN TIGA DESA AEK NAULI 2 KEC.POLLUNG,DS AEK NAULI 2,POLLUNG,HUMBANG HASUNDUTAN,HURLEY INC,4904.0,HUMBANG HASUNDUTAN,DLS,PROVINSI SUMATERA UTARA,SUMBAGUT,1,014,DLS-01-014
5358,100000059265,DESA PANSUR NATOLU KEC.PANGARIBUAN,DS PANSUR NATOLU,PANGARIBUAN,TAPANULI UTARA,WRIGHT-GARZA,4905.0,TAPANULI UTARA,TRT,PROVINSI SUMATERA UTARA,SUMBAGUT,1,015,TRT-01-015
2383,100000059267,JL.BANGLAS GG DAMAI RT.02/02,DS SELATPANJANG TIMUR,TEBING TINGGI,KEPULAUAN MERANTI,BENTON-PEREZ,4906.0,KEPULAUAN MERANTI,TTG,PROVINSI RIAU,SUMBAGTENG,2,010,TTG-02-010
5359,100000059268,DESA BANUAJI I KEC.ADIANKOTING,DS BANUAJI I,ADIANKOTING,TAPANULI UTARA,INGRAM-BROWN,4907.0,TAPANULI UTARA,TRT,PROVINSI SUMATERA UTARA,SUMBAGUT,1,016,TRT-01-016
1606,100000059270,DESA PERJUANGAN KEC.SUMBUL KAB.DAIRI,DS PERJUANGAN,SUMBUL,DAIRI,"BLACKWELL, RICHARDS AND SANDERS",4908.0,DAIRI,SDK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,017,SDK-01-017

In [51]:
# Mengekspor DataFrame merged_df_assessment ke file Excel
merged_df_assessment.to_excel('merged_df_assessment_final.xlsx', index=False)

In [52]:
merged_df_assessment.columns

Index(['Funcloc', 'Alamat1', 'Alamat2', 'Alamat3', 'Alamat4', 'SiteName',
       'Funcloc_Order', 'City', 'CityCode', 'Province', 'Region',
       'RegionalCode', 'Sequence', 'Internal Site ID'],
      dtype='object')

In [53]:
merged_df_assessment = merged_df_assessment[['Internal Site ID','Alamat4','Alamat1','City','CityCode','Province', 'Region',
                      'RegionalCode', 'Funcloc']]

In [54]:
merged_df_assessment

,Internal Site ID,Alamat4,Alamat1,City,CityCode,Province,Region,RegionalCode,Funcloc
947,AGM-03-001,BENGKULU UTARA,DESA ALUN DUA,BENGKULU UTARA,AGM,PROVINSI BENGKULU,SUMBAGSEL,3,100000000002
2755,AKK-01-001,LABUHAN BATU UTARA,DESA PADANG MANINJAU,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,100000000003
2756,AKK-01-002,LABUHAN BATU UTARA,DESA BIO-BIO,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,100000000004
2757,AKK-01-003,LABUHAN BATU UTARA,RINTIS KACANG,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,100000000005
2758,AKK-01-004,LABUHAN BATU UTARA,DUSUN VI SIDODADI,LABUHAN BATU UTARA,AKK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,100000000006
...,...,...,...,...,...,...,...,...,...
1899,DLS-01-014,HUMBANG HASUNDUTAN,DUSUN TIGA DESA AEK NAULI 2 KEC.POLLUNG,HUMBANG HASUNDUTAN,DLS,PROVINSI SUMATERA UTARA,SUMBAGUT,1,100000059183
5358,TRT-01-015,TAPANULI UTARA,DESA PANSUR NATOLU KEC.PANGARIBUAN,TAPANULI UTARA,TRT,PROVINSI SUMATERA UTARA,SUMBAGUT,1,100000059265
2383,TTG-02-010,KEPULAUAN MERANTI,JL.BANGLAS GG DAMAI RT.02/02,KEPULAUAN MERANTI,TTG,PROVINSI RIAU,SUMBAGTENG,2,100000059267
5359,TRT-01-016,TAPANULI UTARA,DESA BANUAJI I KEC.ADIANKOTING,TAPANULI UTARA,TRT,PROVINSI SUMATERA UTARA,SUMBAGUT,1,100000059268
1606,SDK-01-017,DAIRI,DESA PERJUANGAN KEC.SUMBUL KAB.DAIRI,DAIRI,SDK,PROVINSI SUMATERA UTARA,SUMBAGUT,1,100000059270